/**
 * Bundled Karel assignments.
 *
 * Each assignment is a manifest object. There are two shapes, both handled by the
 * student page (assignments/assignment.html → assignment.js) and the graders:
 *   - lesson assignments (lesson-NN.js) — one per lessons/NN-*.html page, each
 *     bundling three problems (simple / moderate / complex), sometimes more
 *     under an extra key. GENERATED by tools/gen-lesson-assignments.js.
 *   - standalone assignments (collect-all.js) — a single problem at the top level.
 * Every problem stores its reference solution SEALED (see tools/seal.js).
 *
 *   import { assignments, getAssignment } from "./assignments/index.js";
 *   const a = getAssignment("lesson-01");
 *
 * This is the single source of truth for which assignments exist; both the
 * student page and the teacher graders (tools/grade.js, tools/grade-lessons.js)
 * import from here. To regenerate the lesson assignments after editing a problem,
 * run `node tools/gen-lesson-assignments.js`.
 */
export { collectAll } from "./collect-all.js";
export { lesson01 } from "./lesson-01.js";
export { lesson02 } from "./lesson-02.js";
export { lesson03 } from "./lesson-03.js";
export { lesson04 } from "./lesson-04.js";
export { lesson05 } from "./lesson-05.js";
export { lesson06 } from "./lesson-06.js";
export { lesson07 } from "./lesson-07.js";
export { lesson08 } from "./lesson-08.js";
export { lesson09 } from "./lesson-09.js";
export { lesson10 } from "./lesson-10.js";
export { lesson11 } from "./lesson-11.js";
export { lesson12 } from "./lesson-12.js";
export { lesson13 } from "./lesson-13.js";
export { lesson14 } from "./lesson-14.js";
export { lesson15 } from "./lesson-15.js";
export { lesson16 } from "./lesson-16.js";
export { lesson17 } from "./lesson-17.js";
export { lesson18 } from "./lesson-18.js";

import { collectAll } from "./collect-all.js";
import { lesson01 } from "./lesson-01.js";
import { lesson02 } from "./lesson-02.js";
import { lesson03 } from "./lesson-03.js";
import { lesson04 } from "./lesson-04.js";
import { lesson05 } from "./lesson-05.js";
import { lesson06 } from "./lesson-06.js";
import { lesson07 } from "./lesson-07.js";
import { lesson08 } from "./lesson-08.js";
import { lesson09 } from "./lesson-09.js";
import { lesson10 } from "./lesson-10.js";
import { lesson11 } from "./lesson-11.js";
import { lesson12 } from "./lesson-12.js";
import { lesson13 } from "./lesson-13.js";
import { lesson14 } from "./lesson-14.js";
import { lesson15 } from "./lesson-15.js";
import { lesson16 } from "./lesson-16.js";
import { lesson17 } from "./lesson-17.js";
import { lesson18 } from "./lesson-18.js";

/** The 18 per-lesson assignments, in course order. */
export const lessonAssignments = [
  lesson01, lesson02, lesson03, lesson04, lesson05, lesson06,
  lesson07, lesson08, lesson09, lesson10, lesson11, lesson12,
  lesson13, lesson14, lesson15, lesson16, lesson17, lesson18,
];

/** All assignments, in the order they should appear on the index page. */
export const assignments = [...lessonAssignments, collectAll];

/** Look up an assignment manifest by its `id`, or undefined if none matches. */
export function getAssignment(id) {
  return assignments.find(a => a.id === id);
}
