/**
 * Assignment "lesson-10" — companion to lessons/10-capstone.html (Putting It All Together).
 *
 * GENERATED by tools/gen-lesson-assignments.js — edit the problem there and
 * regenerate; do not hand-edit the sealed solutions below. Each of the three
 * problems (simple / moderate / complex) stores its reference solution SEALED
 * (see tools/seal.js). The plaintext solutions live in the generator.
 */
export const lesson10 = {
  id: "lesson-10",
  lessonNum: 10,
  lessonSlug: "10-capstone",
  lessonTitle: "Putting It All Together",
  title: "Assignment 10 · Putting It All Together",
  points: 30,
  problems: [
    {
      key: "simple",
      label: "Simple",
      points: 5,
      world: "Dimension: (4, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Warm-up: fill the whole row — drop a beeper on all four corners.",
      starter: "function main(k) {\n  \n}\n",
      check: ["beepers","position"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WVwQTUk0ASBdTWBALQR1IRQhMWUQeTRECSllMTFZpUxEQFgoDAxAVLgABXRNDQ0hJb0wNQ1NaHlsOWxZNSFdvRA0LO0tBGUscWBcxVFVGBF9bTFpmGA==",
    },
    {
      key: "moderate",
      label: "Moderate",
      points: 10,
      world: "Dimension: (3, 3)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Fill the entire 3×3 grid with beepers, one on every corner. Sweep the rows in a snake (boustrophedon) pattern so you never waste moves.",
      starter: "function turnRight(k) {\n  k.turnLeft();\n  k.turnLeft();\n  k.turnLeft();\n}\n\nfunction main(k) {\n  \n}\n",
      check: ["beepers"],
      solution: "DRQcBhhEDB0RREMTQyEMBgQRTEZfERBrUkUHAxcGQ156BEsHTUhXb0QNHR8fFAALIEgFBxkZDWsNUw5PGBAWQzpUDRVaTFcnHnk7VkMPTgcMDgJFCUwfX0MKW0UXJ0NTV19EQQUfABVMFwtaVgxLUUlFHkIUUw0QBVoNAQoWR05NDQ07S0FSRQpCEVMZXFMVDRpFXExVXw0fEVdBQV5MREhYGBBNaw1TRUFMRQ8DBkQfIxcAHEgRWxgLPEENU0VBTAwCDV5YS11SV0UNCF1cX0AEBVpea0xFRA0LO0tBUkUFS0NbQ19BQRFTV0hMHm4NVhFLQVIMCg1LGB9WVwJEHQIkDRYQBV8YSxpSDkJZFgFffFMHWVtMWkwOSkAZRw5JW15MRk0HREJYLUgVEUlFXkRQfBFLQVJFTEgPAFQQTUFZBhcPPgwDRQIZAEhJRQcDDhxHVR5IFlMRFB4LNkQRWR9JGUxXDR55ERAWQVB5RUERbxk=",
    },
    {
      key: "complex",
      label: "Complex",
      points: 15,
      world: "Dimension: (4, 4)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Climb the diagonal: drop a beeper on <code>(1, 1)</code>, <code>(2, 2)</code>, <code>(3, 3)</code>, and <code>(4, 4)</code>, using a step of \"east one, north one\" between drops.",
      starter: "function turnRight(k) {\n  k.turnLeft();\n  k.turnLeft();\n  k.turnLeft();\n}\n\nfunction main(k) {\n  \n}\n",
      check: ["beepers","position"],
      solution: "DRQcBhhEDB0RREMTQyEMBgQRTEZfERBrUkUHAxcGQ156BEsHTUhXb0QNHR8fFAALIEgFBxkZDWsNUw5PGBAWQzpUDRVaTFcnHnk7VkMPTgcMDgJFCUwfX0MKW0UXJ0NTV19EQQUfABVMDEQQVgFQQRtFUA1XSBFZHUoEUx5rTEVEDR0fGxQGJwlIExZDGB9aJ1NFQUwMAg1eWEtdUlZFDRh5ERAWQQ1TDk8BChJIXhhQa1JFTA1DU1oeQhRfHSkEChFMBE07S0FSRUwNCF1cX0AEBVpea0xFRA1WER8UAAs+RAQbRRhdSBZ5RUFMRRknVhEWaw8=",
    },
  ],
};

export default lesson10;
