/**
 * Assignment "lesson-01" — companion to lessons/01-commands.html (Commands & Sequencing).
 *
 * GENERATED by tools/gen-lesson-assignments.js — edit the problem there and
 * regenerate; do not hand-edit the sealed solutions below. Each of the three
 * problems (simple / moderate / complex) stores its reference solution SEALED
 * (see tools/seal.js). The plaintext solutions live in the generator.
 */
export const lesson01 = {
  id: "lesson-01",
  lessonNum: 1,
  lessonSlug: "01-commands",
  lessonTitle: "Commands & Sequencing",
  title: "Assignment 1 · Commands & Sequencing",
  points: 30,
  problems: [
    {
      key: "simple",
      label: "Simple",
      points: 5,
      world: "Dimension: (5, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Karel starts at the west end of a 5-corner corridor. Walk east until Karel stands on the last corner <code>(5, 1)</code>.",
      starter: "function main(k) {\n  \n}\n",
      check: ["position"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WWkUMHRMJBUpIOxAWCgMeChcJTU0WfBFLClwIA1sGWxgLPEENGEsMAxMBBV8KYRw=",
    },
    {
      key: "moderate",
      label: "Moderate",
      points: 10,
      world: "Dimension: (4, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Drop a beeper on the <strong>first</strong> corner, walk east to corner <code>(4, 1)</code>, and drop a beeper there too.",
      starter: "function main(k) {\n  \n}\n",
      check: ["beepers","position"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WWkURBxEuSAYDVEIeSBZ5RUEHSwlCAFRDSElvTA0IXVxfQAQFWl5rTEUPAxteHQRaTFcnQ1NaHkYUWTEABBwAFgVfCmEc",
    },
    {
      key: "complex",
      label: "Complex",
      points: 15,
      world: "Dimension: (3, 3)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Walk east to the far wall, turn to face north, walk up to the top-right corner <code>(3, 3)</code>, and drop a single beeper there. Karel should finish facing north.",
      starter: "function main(k) {\n  \n}\n",
      check: ["beepers","position","direction"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WWkUMHRMJBUpIOxAWCgMeChcJTU0WfBFLClwRGV8NP1RWQkkESG9BTA5KQBlHDklbXmYNQxgfXVkXSFtMWmZFREZYQR4VMAAJXQYBGRkNa1A=",
    },
  ],
};

export default lesson01;
