/**
 * Assignment "lesson-03" — companion to lessons/03-if.html (Making Decisions with if).
 *
 * GENERATED by tools/gen-lesson-assignments.js — edit the problem there and
 * regenerate; do not hand-edit the sealed solutions below. Each of the three
 * problems (simple / moderate / complex) stores its reference solution SEALED
 * (see tools/seal.js). The plaintext solutions live in the generator.
 */
export const lesson03 = {
  id: "lesson-03",
  lessonNum: 3,
  lessonSlug: "03-if",
  lessonTitle: "Making Decisions with if",
  title: "Assignment 3 · Making Decisions with if",
  points: 30,
  problems: [
    {
      key: "simple",
      label: "Simple",
      points: 5,
      world: "Dimension: (1, 1)\nKarel: (1, 1); east\nBeeperBag: 0\nBeeper: (1, 1); 1",
      prompt: "There may or may not be a beeper here. Using a single <code>if</code>, pick the beeper up <strong>only if</strong> one is present.",
      starter: "function main(k) {\n  \n}\n",
      check: ["beepers"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WWA1BWg5CTwYWQVVEEn0BABIJCxAFXxhLGnhFTA1DGB9AXwJGMQAEHAAWBV8KYUFSGGZQ",
    },
    {
      key: "moderate",
      label: "Moderate",
      points: 10,
      world: "Dimension: (3, 1)\nKarel: (1, 1); east\nBeeperBag: 0\nBeeper: (1, 1); 1\nBeeper: (3, 1); 1",
      prompt: "Some corners have a beeper, some don't. Visit all three corners in a row (no loop yet — write it out). At each corner, pick a beeper up only if one is present.",
      starter: "function main(k) {\n  \n}\n",
      check: ["beepers","position"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WWA1BWg5CTwYWQVVEEn0BABIJCxAFXxhLClwVBU4IMVRVRgRfW0xaZkVERlhcBBcXTUUWaVMRWVBBBRhLAwkAFEgEQjsTFxYJQxdbGBkWCgMDDAIHJwFIBlQZSVteZg1DGB9dWRdIW0xaZkVERBARQwpcBwlIExZDQ2YTSAAADxhNTQRWWkURGwYHbwYWQVVESQRIbxw=",
    },
    {
      key: "complex",
      label: "Complex",
      points: 15,
      world: "Dimension: (4, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY\nBeeper: (2, 1); 1\nBeeper: (4, 1); 1",
      prompt: "Walk across all four corners. Whenever the current corner has a beeper, paint it <code>\"Red\"</code>. Leave the beepers where they are.",
      starter: "function main(k) {\n  \n}\n",
      check: ["colors","position"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WWA1BWg5CTwYWQVVEEn0BABIJCxAFXxhLClwVDUQNB3JfRA9IAU1DPgAAD18KYUFSDkJADAVUGB9aJ1NFCApFTEZYUw4EAgAeXjMBVENTD1lbTEhMDkpdF1gFFTEKHkMGARkSZARJUUxaZkVERlhcBBcXTUUWaVMRWVBBBRhLAwkAFEgEQjsTFxYJQxdbGBkWCgMDBAgCESdCBF8OE1pHPkgHURgLPEENGEsMAxMBBV8KYUFSDAoNSxgfUlMEXRYXEjwXAV4TXx9JW0xMRk0DUFlYFW4cFw8JF0wPJFQPQ1teZlA=",
    },
  ],
};

export default lesson03;
