/**
 * Assignment "lesson-04" — companion to lessons/04-for-loops.html (The for Loop).
 *
 * GENERATED by tools/gen-lesson-assignments.js — edit the problem there and
 * regenerate; do not hand-edit the sealed solutions below. Each of the three
 * problems (simple / moderate / complex) stores its reference solution SEALED
 * (see tools/seal.js). The plaintext solutions live in the generator.
 */
export const lesson04 = {
  id: "lesson-04",
  lessonNum: 4,
  lessonSlug: "04-for-loops",
  lessonTitle: "The for Loop",
  title: "Assignment 4 · The for Loop",
  points: 30,
  problems: [
    {
      key: "simple",
      label: "Simple",
      points: 5,
      world: "Dimension: (6, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Use a <code>for</code> loop to move east five times, ending on <code>(6, 1)</code>.",
      starter: "function main(k) {\n  \n}\n",
      check: ["position"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WVwQTUk0ASBdTWBALQR1IRQhMWUQYTRECSllMTFZpUxEQFgoDHgoXCU1NFnwRSxx4GA==",
    },
    {
      key: "moderate",
      label: "Moderate",
      points: 10,
      world: "Dimension: (5, 5)\nKarel: (1, 1); east\nBeeperBag: 0\nBeeper: (1, 1); 1\nBeeper: (2, 2); 1\nBeeper: (3, 3); 1\nBeeper: (4, 4); 1\nBeeper: (5, 5); 1",
      prompt: "A beeper sits on every corner of the diagonal, from <code>(1, 1)</code> up to <code>(5, 5)</code>. Use a <code>for</code> loop to walk the diagonal, picking up each beeper along the way, and finish on <code>(5, 5)</code>. Karel can only <code>turnLeft()</code>, so one step to the northeast means: move east, turn to face north, move north, then turn back to face east.",
      starter: "function main(k) {\n  \n}\n",
      check: ["beepers","position"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WVwQTUk0ASBdTWBALQR1IRQhMWUQZTRECSllMTFZpUxEQFgoDAwwCBycBSAZUGUlbXmYNQ1MRWxgMQgUASUVebg1WEUsKXBEZXw0/VFZCSQRIb0FMRURGWFwEFxdNRRZpUxEQFgoDBxATAikBSwIZQlp4RUwNQxgfREMTQz8ABxhNTRZ8EUtBUg5CWRYBX3xTB1lbTFpmRURQfBFLClwVBU4IMVRVRgRfW0xaZhg=",
    },
    {
      key: "complex",
      label: "Complex",
      points: 15,
      world: "Dimension: (5, 5)\nKarel: (1, 1); east\nBeeperBag: 0\nBeeper: (1, 1); 1\nBeeper: (2, 1); 1\nBeeper: (3, 1); 1\nBeeper: (4, 1); 1\nBeeper: (5, 1); 1\nBeeper: (5, 2); 1\nBeeper: (5, 3); 1\nBeeper: (5, 4); 1\nBeeper: (5, 5); 1\nBeeper: (4, 5); 1\nBeeper: (3, 5); 1\nBeeper: (2, 5); 1\nBeeper: (1, 5); 1\nBeeper: (1, 4); 1\nBeeper: (1, 3); 1\nBeeper: (1, 2); 1\nBeeper: (2, 2); 1\nBeeper: (3, 3); 1\nBeeper: (4, 4); 1",
      prompt: "This 5&times;5 world has a beeper on all 16 perimeter corners and one on each interior diagonal corner &mdash; <code>(2, 2)</code>, <code>(3, 3)</code>, <code>(4, 4)</code>. Pick up every beeper with two loops, one after the other.\n<p><strong>1. A nested loop for the perimeter.</strong> The outer loop runs once per side (four sides). The inner loop walks that side &mdash; <code>pickBeeper()</code> then <code>move()</code>, four times. After the inner loop, <code>turnLeft()</code> to face the next side. Four sides later Karel is back where it started, facing east.</p>\n<p><strong>2. A simple loop for the diagonal.</strong> Three times: step one corner to the north-east (<code>move()</code>, <code>turnLeft()</code>, <code>move()</code>, <code>turnRight(k)</code>) and <code>pickBeeper()</code>.</p>\n<p>The <code>turnRight</code> helper is already written for you.</p>",
      starter: "function turnRight(k) {\n  k.turnLeft();\n  k.turnLeft();\n  k.turnLeft();\n}\n\nfunction main(k) {\n  // Loop 1: walk the perimeter (outer loop = 4 sides, inner loop = 4 steps)\n\n  // Loop 2: climb the diagonal, picking up (2,2), (3,3), (4,4)\n\n}\n",
      check: ["beepers"],
      solution: "DRQcBhhEDB0RREMTQyEMBgQRTEZfERBrUkUHAxcGQ156BEsHTUhXb0QNHR8fFAALIEgFBxkZDWsNUw5PGBAWQzpUDRVaTFcnHnk7VkMPTgcMDgJFCUwfX0MKW0UXJ0NTV19EQQUfABVMFg1JExFWQUJeTF4KF1QQCkEZSEUSBQEBBl0YSxp4RUwNQxVeQhZJQRYRQR8RAV1WDEtRSUUfWQYDEQwWVRZTFhUJFU8GXxEQa1JFTA1DU1oeRghOGCcECRUBX14YUGtSRUwNQ1NaHlsOWxZNSFdvRA1WERZrUkVMDQhdRUVED2EWAxVETF8nVhEWa1JFCkIRUxlcUxUNGkVcTFVfDR8RV0FBXkxESFgYEE1rDVNFQQdLCUIAVENISW9MDUNTWh5CFF8dKQQKEUwETTtLQVJFBwMOHEdVHkgWeUVBTEUQWARfOQgVDRgFCFoKOhZBDVMOTxwMB0Y0VA4RFxdEBFh5ERBLa1A=",
    },
  ],
};

export default lesson04;
