/**
 * Assignment "lesson-11" — companion to lessons/11-numbers-operators.html (Numbers & Operators).
 *
 * GENERATED by tools/gen-lesson-assignments.js — edit the problem there and
 * regenerate; do not hand-edit the sealed solutions below. Each of the three
 * problems (simple / moderate / complex) stores its reference solution SEALED
 * (see tools/seal.js). The plaintext solutions live in the generator.
 */
export const lesson11 = {
  id: "lesson-11",
  lessonNum: 11,
  lessonSlug: "11-numbers-operators",
  lessonTitle: "Numbers & Operators",
  title: "Assignment 11 · Numbers & Operators",
  points: 30,
  problems: [
    {
      key: "simple",
      label: "Simple",
      points: 5,
      world: "Dimension: (1, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Compute <code>2 + 3</code>, store it in a variable, and drop that many beepers on the corner.",
      starter: "function main(k) {\n  const n = 2 + 3;\n  \n}\n",
      check: ["beepers"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WUgQPARFMQ0NOEQIWSg1AXmtMRQJCBBFDDRcRTERDThEADUFEU1lBAl5ERF0aQkEZSxxYFzFUVUYEX1tMWmYY",
    },
    {
      key: "moderate",
      label: "Moderate",
      points: 10,
      world: "Dimension: (7, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Compute <code>2 * 3</code> and move Karel that many squares east, ending on <code>(7, 1)</code>.",
      starter: "function main(k) {\n  const steps = 2 * 3;\n  \n}\n",
      check: ["position"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WUgQPARFMXhcWQUMWXA1BRUtMVl8nVhENDgBFREEGBxFZFlwNQ15BBUVYDQVFDhEBXkxESFgYEF1PQBwTBERMXycL",
    },
    {
      key: "complex",
      label: "Complex",
      points: 15,
      world: "Dimension: (6, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Use the remainder operator <code>%</code>: walk all six corners and paint the even-numbered ones (corner 2, 4, 6) <code>\"Red\"</code>. Corner numbers are 1-based.",
      starter: "function main(k) {\n  \n}\n",
      check: ["colors","position"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WVwQTUk0ASBdTWBALQRxIRQhMWVkNQApLCFlORQ0YeREQFkFEFUVJBUVBDUQRVlxPRVwEQxgfQFcIQwcmDh4LAV9eEzkEFkdFFmlTERAWCEtTTQhMWUQbXxEATx8KGkhLWgo6FkFQeRg=",
    },
  ],
};

export default lesson11;
