/**
 * Assignment "lesson-11" — companion to lessons/11-numbers-operators.html (Numbers & Operators).
 *
 * GENERATED by tools/gen-lesson-assignments.js — edit the problem there and
 * regenerate; do not hand-edit the sealed solutions below. Each of the three
 * problems (simple / moderate / complex) stores its reference solution SEALED
 * (see tools/seal.js). The plaintext solutions live in the generator.
 */
export const lesson11 = {
  id: "lesson-11",
  lessonNum: 11,
  lessonSlug: "11-numbers-operators",
  lessonTitle: "Numbers & Operators",
  title: "Assignment 11 · Numbers & Operators",
  points: 30,
  problems: [
    {
      key: "simple",
      label: "Simple",
      points: 5,
      world: "Dimension: (20, 20)\nKarel: (1, 3); east\nBeeperBag: INFINITY\nBeeper: (1, 3); 1\nBeeper: (2, 3); 1\nBeeper: (5, 3); 1\nBeeper: (6, 3); 1\nBeeper: (7, 3); 1\nBeeper: (1, 4); 1\nBeeper: (2, 4); 1\nBeeper: (3, 4); 1\nBeeper: (5, 4); 1\nBeeper: (1, 5); 1\nBeeper: (5, 5); 1\nBeeper: (6, 5); 1\nBeeper: (1, 6); 1\nBeeper: (2, 6); 1\nBeeper: (5, 6); 1\nBeeper: (6, 6); 1",
      prompt: "Karel stands at the start of street 3, facing east. Four streets (3&ndash;6) each hold two groups of beepers: a <strong>left group</strong> in avenues 1&ndash;3 and a <strong>right group</strong> in avenues 5&ndash;7, each with 1, 2 or 3 beepers on that street. Process <em>each street individually</em>: count the beepers in its left group and in its right group, store the two counts in variables, then use a <code>for</code> loop over their <em>sum</em> to lay out that many beepers in a row on the same street, starting at avenue 9 (to the right of both groups). Leave the original beepers where they are.",
      starter: "function main(k) {\n  \n}\n",
      check: ["beepers"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WVwQTUk0ASBdTQ19BQRBTVVpMFwtaVg1LVUlFHkIUWBoZFhonU0VBTAkBWVZdDgcGRVENU0g7EBZBDR8AFUwXDUoeRUtcUlVXJ0NTERBQDl9TTQ0JEURMAFQFFBdFUQ1SSBFRQARDBgBBUFhEGk0RChcXCxlISFgYEE1rDVNFQUxFDUtWGQBPEAAJXQYBQmBEBF4WCxVETE0NDTtLQVJFTA1DU1hWFklMBQAPGQBEEUsRWEhSCQlLF1MMEFoESwdFSkxUXydWEUtBUkVMDQYfQlUWE0QUDRVMWERfH1YDFVJOTBxYeREQFkENUxhrTEVEDVYRAgdSTQ1bBh1EVRZdDURMQQdLCUIAVENISW9MDUNTTDoWQQ1TDk8BChJIXhhQa1JFTA0IXVxfQAQFWl5rTEVEDRVeBRIGRRhCFxJdEAtBQRYDFUxORF8fVgMVSW9MDUNTV19EQQUfABVMDEQQVgFQQRtFUA0XHEVRWloNGk5KRUUfJ1YRS0FSRQcDEwZFclMEXRYXSUVebg1WEUtBUg5CQAwFVBgfWidTRUFMGG4NVhFLClwRGV8NP1RWQkkESG9BTEVERlhFHhMcKQlLF1sYCzxBDVNFBwMXRAUaVB9BG0VRDVNIEVkWXQ1LRUpMEQtZF11QQRtORwRDGB9dWRdIW0xaZkVEDVZYDUFaFwNaQ08RAx9BVnlFQUxFRA0QXhlBWgkJWUMaEQ0WURZTDEFQRVcWVlhASltFBwMXBkNeegRLB01IV29EDVYRS0EZSwFCFRYZGQ1rDVNFQUxFAkIEEUMNFxFMRENOEQANQURTWUFfXkREXRpCQRlLGFgRHX1VUBUFWl5rTEVEDQs7S0EPbxE=",
    },
    {
      key: "moderate",
      label: "Moderate",
      points: 10,
      world: "Dimension: (6, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Karel has <strong>17</strong> beepers to pack into boxes that each hold <strong>5</strong>. Starting on avenue 1 and facing east, put one full box (5 beepers) on each corner for as many <em>whole</em> boxes as fit, then put the <em>leftover</em> beepers on the next corner. That is 5, 5, 5 on avenues 1&ndash;3 and 2 on avenue 4. Store <code>17</code> and <code>5</code> in variables and <em>compute</em> the number of full boxes with <code>Math.floor(17 / 5)</code> and the leftover with <code>17 % 5</code>&mdash;don't type <code>3</code> or <code>2</code> yourself. Where Karel ends up is up to you.",
      starter: "function main(k) {\n  \n}\n",
      check: ["beepers"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WUgQPARFMWQwHUFwWXA1CUlpmRUROGV8YFVIWBVcGUwwQA1onU0UCAwsXWVZTBBkXFkwQQz5QRF5PSx8KDh5NEEICUAdBXUUfRBkWGAs8QQ0QCg8fEURBE1cfDgQAHg1eU0VfQgBBU0BBHwweSE07S0EUCh4NSx9URBYDDU5FUVdFBg1KEQkOCgAfFkMRGhsfQVZ5RUFMRQJCBBFDDRcRTERDThEADUFEU1lBHwweSE0RAkpZTExGTQNERHQESAMAE0RMXydWEUtBGUsBQhUWGRkNaw1TGGtMRQJCBBFDDRcRTERDThEADUFEU1lBAAACWRlHDhNJRQUGSFoRWxgRWAcnBAkVAV9eGFBrDw==",
    },
    {
      key: "complex",
      label: "Complex",
      points: 15,
      world: "Dimension: (7, 6)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "A multiplication table, wrapped around. On every corner of the 7&times;6 world, put down <code>(avenue * street) % 5</code> beepers: so <code>(3, 4)</code> gets <code>12 % 5 = 2</code> beepers, and <code>(5, 2)</code> gets none. Karel starts on <code>(1, 1)</code> facing east, and the world is empty to begin with. Keep track of the current avenue and street in variables, and let <code>%</code> decide how many beepers each corner gets. Where Karel ends up is up to you.",
      starter: "function main(k) {\n  \n}\n",
      check: ["beepers"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WVwQTUk0ASBdTQkREBEgHRVxMVF8NBUUZBBcRTBFeUwcLFhJZAQAEGE5PBFZKYUFSRUxLDAERGFoEWVMEFwkLEUhWDEtQSUUNWwYdRFUWXRBTUlpMBBJIGEQOSllMTFZpUxEQFkENEAoPHxFEThlEBRVSWEwFAgVUXkMEDVlFEhgXAUgCGEtEUlBXJ0NTERAWQUscF0FECQFZVlhLXFJVVw0KUw0QVQ5YHRFaTAxPBl8RAE8CEBhvBhZBVURJBEhvQUxFRA1WWA1BWgQaSA0GVBAKQRpaRQpCCAtbExlCWnhFTA1DDjsQFkENGEsVGRcKYRNXH0lbXmYNQ1MRWxgVWAELLQkDEAVfCmFBUkVMSwwBERhaBFlTDEFRRVQWVlhLXVJTVw0KWBoZFgoDHgoXCU1NFnwRS0FSDkJZFgFffFMHWVtMWmZFRA1WWkUVBxcCYQYVRRgfWidTRUFMDAINXkIfExcAGA1fUwcZFhonU0VBTEVERlhFHhMcKQlLF1sYCzxBDVNFQUwOSkAZRw5JW15mDUNTERAWCgMHEBMCKQFLAhlCWnhFTA1DUxFbGBVYAQstCQMQBV8KYUFSRUwNQxgfREMTQz8ABxhNTRZ8EUtBUhhmDUMOO00=",
    },
  ],
};

export default lesson11;
