/**
 * Assignment "lesson-05" — companion to lessons/05-while-loops.html (The while Loop).
 *
 * GENERATED by tools/gen-lesson-assignments.js — edit the problem there and
 * regenerate; do not hand-edit the sealed solutions below. Each of the three
 * problems (simple / moderate / complex) stores its reference solution SEALED
 * (see tools/seal.js). The plaintext solutions live in the generator.
 */
export const lesson05 = {
  id: "lesson-05",
  lessonNum: 5,
  lessonSlug: "05-while-loops",
  lessonTitle: "The while Loop",
  title: "Assignment 5 · The while Loop",
  points: 50,
  problems: [
    {
      key: "simple",
      label: "Simple",
      points: 5,
      world: "Dimension: (7, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Karel doesn't know how long the corridor is. Use a <code>while</code> loop to move east until the front is blocked, stopping at the far wall.",
      starter: "function main(k) {\n  \n}\n",
      check: ["position"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WRgMIHgBMBQhdV0JZD1k6FiIAAAVfXhhCQQlvTA1DU1oeWw5bFk1IV29EDQs7Fg==",
    },
    {
      key: "moderate",
      label: "Moderate",
      points: 10,
      world: "Dimension: (6, 1)\nKarel: (1, 1); east\nBeeperBag: 0\nBeeper: (1, 1); 1\nBeeper: (2, 1); 1\nBeeper: (3, 1); 1\nBeeper: (4, 1); 1\nBeeper: (5, 1); 1\nBeeper: (6, 1); 1",
      prompt: "Every corner holds a beeper. Walk east to the wall, collecting <strong>every</strong> beeper along the way, and stop on the last corner.",
      starter: "function main(k) {\n  \n}\n",
      check: ["beepers","position"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WRgMIHgBMBRcBRFUfQVZ5RUFMRRNFH10OQVoOQk8GFkFVRBJ9AQASCQsQBV8YSwpcFQVOCDFUVUYEX1tMWmZFRA1WWA1BWkQHAwUBXl5CKF4wCQQNF0wEXxEJExcEBxZpUxEQFgoDHgoXCU1NFnwRSxx4GA==",
    },
    {
      key: "complex",
      label: "Complex",
      points: 15,
      world: "Dimension: (8, 8)\nKarel: (1, 1); east\nBeeperBag: 0\nBeeper: (1, 1); 1\nBeeper: (1, 2); 2\nBeeper: (1, 3); 3\nBeeper: (1, 4); 4\nBeeper: (1, 5); 5\nBeeper: (1, 6); 6\nBeeper: (1, 7); 7\nBeeper: (1, 8); 8",
      prompt: "Eight piles of beepers sit along avenue 1 &mdash; one per street, and each pile is <strong>as many beepers as its street number</strong> (street 1 has 1 beeper, street 2 has 2, &hellip; street 8 has 8). Karel starts on <code>(1, 1)</code> facing east with an empty bag.\n<p>For every street, carry that street's entire pile from avenue 1 across to avenue 8 and drop it there, then move on to the next street.</p>\n<p>Use <code>while</code> loops to pick up and drop each pile &mdash; <code>beepersPresent()</code> and <code>beepersInBag()</code> tell Karel when a pile (or its own bag) is empty.</p>",
      starter: "function main(k) {\n  \n}\n",
      check: ["beepers"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WRgMIHgBMBRcBRFUfQVZ5RUFMRRNFH10OQVoOQk8GFkFVRBJ9AQASCQsQBV8YSwpcFQVOCDFUVUYEX1tMWmZFRA1WRgMIHgBMBQhdV0JZD1k6FiIAAAVfXhhCQRlLAUIVFhkZDWsNU0VBGw0NQRMRQwpcBwlIExZDQ38PbxICSUVMREZYQR4VMAAJXQYBGRkNaw1TRUEFA0QFV1pFDRcDGGQQMF1VVxMFWkxBDhcBTB0KYUFSRUxGTQdEQlgtSBURSUVebg1WEUsKXAgDWwZbGAs8QQ1TRQpCERFfGH0OBwZNRRZpUxEQFhZFGgkETE0PAxBDBA8GLB9uDxZQQh5IBFMOTwEKEkheGFBrUkVMDQhdRUVED2EWAxVETF8nVhFLQRlLGFgRHX1VUBUFWl5rTEUZJws=",
    },
    {
      key: "complex2",
      label: "Complex II",
      points: 20,
      world: "Dimension: (16, 16)\nKarel: (1, 1); east\nBeeperBag: 0\nWall: (1, 3); north\nWall: (16, 5); north\nWall: (1, 7); north\nWall: (16, 9); north\nWall: (1, 11); north\nWall: (16, 13); north\nWall: (1, 15); north\nBeeper: (2, 3); 1\nBeeper: (3, 3); 1\nBeeper: (4, 3); 1\nBeeper: (5, 3); 1\nBeeper: (6, 3); 1\nBeeper: (7, 3); 1\nBeeper: (8, 3); 1\nBeeper: (9, 3); 1\nBeeper: (10, 3); 1\nBeeper: (11, 3); 1\nBeeper: (12, 3); 1\nBeeper: (13, 3); 1\nBeeper: (14, 3); 1\nBeeper: (15, 3); 1\nBeeper: (3, 5); 1\nBeeper: (4, 5); 1\nBeeper: (5, 5); 1\nBeeper: (6, 5); 1\nBeeper: (7, 5); 1\nBeeper: (8, 5); 1\nBeeper: (9, 5); 1\nBeeper: (10, 5); 1\nBeeper: (11, 5); 1\nBeeper: (12, 5); 1\nBeeper: (13, 5); 1\nBeeper: (14, 5); 1\nBeeper: (4, 7); 1\nBeeper: (5, 7); 1\nBeeper: (6, 7); 1\nBeeper: (7, 7); 1\nBeeper: (8, 7); 1\nBeeper: (9, 7); 1\nBeeper: (10, 7); 1\nBeeper: (11, 7); 1\nBeeper: (12, 7); 1\nBeeper: (13, 7); 1\nBeeper: (5, 9); 1\nBeeper: (6, 9); 1\nBeeper: (7, 9); 1\nBeeper: (8, 9); 1\nBeeper: (9, 9); 1\nBeeper: (10, 9); 1\nBeeper: (11, 9); 1\nBeeper: (12, 9); 1\nBeeper: (4, 11); 1\nBeeper: (5, 11); 1\nBeeper: (6, 11); 1\nBeeper: (7, 11); 1\nBeeper: (8, 11); 1\nBeeper: (9, 11); 1\nBeeper: (10, 11); 1\nBeeper: (11, 11); 1\nBeeper: (12, 11); 1\nBeeper: (13, 11); 1\nBeeper: (3, 13); 1\nBeeper: (4, 13); 1\nBeeper: (5, 13); 1\nBeeper: (6, 13); 1\nBeeper: (7, 13); 1\nBeeper: (8, 13); 1\nBeeper: (9, 13); 1\nBeeper: (10, 13); 1\nBeeper: (11, 13); 1\nBeeper: (12, 13); 1\nBeeper: (13, 13); 1\nBeeper: (14, 13); 1\nBeeper: (2, 15); 1\nBeeper: (3, 15); 1\nBeeper: (4, 15); 1\nBeeper: (5, 15); 1\nBeeper: (6, 15); 1\nBeeper: (7, 15); 1\nBeeper: (8, 15); 1\nBeeper: (9, 15); 1\nBeeper: (10, 15); 1\nBeeper: (11, 15); 1\nBeeper: (12, 15); 1\nBeeper: (13, 15); 1\nBeeper: (14, 15); 1\nBeeper: (15, 15); 1\nColor: (1, 16); Red",
      prompt: "A 16&times;16 field is stacked with rows of beepers, one row every other street, forming a diamond that narrows and then widens again as it rises. Short walls pinch each row shut at one end or the other, so there is no way to skip a row &mdash; Karel has to sweep all the way across it before it can climb to the next one.\n<p>Karel starts at <code>(1, 1)</code> facing east with an empty bag and doesn't know how long any row is, how many rows there are, or which end of a row is open for climbing. Corner <code>(1, 16)</code> is painted <code>\"Red\"</code> &mdash; that's the finish line. Keep sweeping and climbing until Karel is standing on that red corner, picking up <strong>every</strong> beeper along the way.</p>\n<p><strong>Hints:</strong></p>\n<ul>\n<li>Nothing here is a fixed number &mdash; not the row length, not the row count, not which side has the opening. Every decision needs to come from a sensing command, not a hardcoded count.</li>\n<li>You've got <code>frontIsClear()</code>, <code>beepersPresent()</code>, and <code>cornerColorIs()</code> to work with. Think about what each one can tell Karel about its surroundings at any given moment, facing any given direction.</li>\n<li><code>cornerColorIs(\"Red\")</code> is how Karel will recognize the finish &mdash; build your overall loop around watching for it rather than trying to count rows.</li>\n</ul>",
      starter: "function main(k) {\n  \n}\n",
      check: ["beepers","position"],
      solution: "DRQcBhhEDB0RVl8PSSEQDz4KEwUdGEsaeEVMWgsaXVUWSUZdAwAPDApKOF4ZFRpNRQ1eThFWVw1eFkxBF29EDVYRAE8GEB5DLxZXRB5IFnlFQRFvRA0BWQINF0VERk0VQ19YFWQAJg0JBBYFXxhLGnhFTA1DGB9dWRdIW0xaZkVEUHwRSwpcERlfDT9UVkJJBEhvQUwMAg1eWkUHAAoCWSoAclxTAF9bTEFRWERLF10YBFtFFydDUxEQXU9ZBhcPIAACWV4YUGtSRUwNCF1FRUQPYRYDFURMXydWERZrUkUbRQofVBAeCgMVFw4CES1eNV0OAABNRQRDCDsQFkENGgNBRA5KTxNUGwQAFjxfBgBUXkJJBFpFGmZFRA1WEUsKXBUFTggxVFVGBF9bTFpmRUQNVkxhQVJFTEZNHl5GU0kESG9BTBhuUHw7DRQcBhhEDB0RXVcIQ1sOSEwebg1WRgMIHgBMBQhdUl9ED0gBJg4AChZkBRlJMxcBTgRDTgwQUABBAABITB5uDVYRSwcbCwh/Fh1jX0FJRlpea0xFGScL",
    },
  ],
};

export default lesson05;
