/**
 * Assignment "lesson-16" — companion to lessons/16-scope.html (Scope & Lifetime).
 *
 * GENERATED by tools/gen-lesson-assignments.js — edit the problem there and
 * regenerate; do not hand-edit the sealed solutions below. Each of the three
 * problems (simple / moderate / complex) stores its reference solution SEALED
 * (see tools/seal.js). The plaintext solutions live in the generator.
 */
export const lesson16 = {
  id: "lesson-16",
  lessonNum: 16,
  lessonSlug: "16-scope",
  lessonTitle: "Scope & Lifetime",
  title: "Assignment 16 · Scope & Lifetime",
  points: 30,
  problems: [
    {
      key: "simple",
      label: "Simple",
      points: 5,
      world: "Dimension: (1, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Write a helper <code>compute()</code> that uses a <strong>local</strong> variable <code>x = 2</code> and returns <code>x + 2</code>. That local is invisible outside the function. Drop <code>compute()</code> beepers (4).",
      starter: "function compute() {\n  \n}\n\nfunction main(k) {\n  \n}\n",
      check: ["beepers"],
      solution: "DRQcBhhEDB0RU1kMXQYRBERMRFZ8EUsNFxFMVUNOEQINaw1TFwQYEBZDVklLSlJXVyceeTtWQw9OBwwOAkUJTB9fQwpbRRcnQ1NSX1gSWVMLQVFFB0IbQR4VF01FFmlTEVZZEw1bCQQYRQ0NSxFbWlIMTBFDHQoQX0oGWkUKQhURWTRUDhEXF0QEWHlM",
    },
    {
      key: "moderate",
      label: "Moderate",
      points: 10,
      world: "Dimension: (5, 1)\nKarel: (1, 1); east\nBeeperBag: 0\nBeeper: (2, 1); 1\nBeeper: (4, 1); 1",
      prompt: "A <code>total</code> variable declared <strong>outside</strong> the loop lives for the whole walk, while the loop's <code>i</code> lives only inside it. Walk all five corners counting the beepers you pick up, then drop <code>total</code> beepers on the last corner.",
      starter: "function main(k) {\n  let total = 0;\n  \n}\n",
      check: ["beepers","position"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WXQ4VUhEDWQIfEQ0WURZ5RUEKChYNXl0OFVIMTBBDQwoQX0ERU1BaTAxPBl8REGtSRUwNChURGF1PTxYAEQkXF30EVBgEHBFEBEpTShBdT10aBgouAAFdE0NDSElFGEIXEl0bHVoNDm9BTEVERBARQwhSWUwZSlNaHlsOWxZNSFdvRA0LO0tBFAoeDUsfVEQWCA1ORVFXRQ0NShEfDgYEABZDGhobH0FGXRUUGCcBSAZUGUlbXmZQ",
    },
    {
      key: "complex",
      label: "Complex",
      points: 15,
      world: "Dimension: (3, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Write <code>fill(k, n)</code> whose loop counter <code>i</code> is local to it. Drive it from <code>main</code> with counts <code>[2, 1, 3]</code> — the two <code>i</code> variables never collide. Drop <code>counts[c]</code> beepers on each corner.",
      starter: "function fill(k, n) {\n  \n}\n\nfunction main(k) {\n  const counts = [2, 1, 3];\n  \n}\n",
      check: ["beepers","position"],
      solution: "DRQcBhhEDB0RVl8NQVsOTUwLTQ0NO0tBFAoeDUsfVEQWCA1ORVFXRQ0NShEFWlIMRwZKU1oeRhRZMQAEHAAWBV8KYRx4bwpYDRBFWVkPDR4ECAJNDwRWSmFBUgYDQxAHEVNZFEMHFkFRRT8fWhFaTVJWMRZpUxFWWRMNWwkEGEUNDUsRW1pSDEwRQxBeRVgVXl0JBAICEEVNEQJKWUxMVmlTERAWB0QfCUkHSUROGUQFFQE+BXBKSDsQFkENGgNBRAxEEVZSBBQcER8DDxZfV0IJDV5FUEVFDwMbXh0EWkxXJ0NTTDpL",
    },
  ],
};

export default lesson16;
