/**
 * Assignment "lesson-07" — companion to lessons/07-parameters.html (Parameters).
 *
 * GENERATED by tools/gen-lesson-assignments.js — edit the problem there and
 * regenerate; do not hand-edit the sealed solutions below. Each of the three
 * problems (simple / moderate / complex) stores its reference solution SEALED
 * (see tools/seal.js). The plaintext solutions live in the generator.
 */
export const lesson07 = {
  id: "lesson-07",
  lessonNum: 7,
  lessonSlug: "07-parameters",
  lessonTitle: "Parameters",
  title: "Assignment 7 · Parameters",
  points: 50,
  problems: [
    {
      key: "simple",
      label: "Easy",
      points: 5,
      world: "Dimension: (5, 4)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Write <code>moveN(k, n)</code> that moves Karel <code>n</code> squares using a <code>for</code> loop. Then use it <strong>twice</strong> from <code>main</code>: walk 4 squares east, turn to face north, and walk 3 squares up to finish on <code>(5, 4)</code>. One function, two different arguments.",
      starter: "function moveN(k, n) {\n  \n}\n\nfunction main(k) {\n  \n}\n",
      check: ["position"],
      solution: "DRQcBhhEDB0RXVkXSD1NCkBFCgRWSmFBUgMDX0NbXVVCQURTWEFcXkREVg1LD0lFBQZIWhFLPEENU0UKQggLWxMZQlp4RUxQaQ47OlAUQxARCAMLREAXWAVJGUxMVmlTEV1ZF0g9TQpARVAETTtLQRlLGFgRHX1VUBUFWl5rTEUJQgBUJUkZSUweSkg7TQ==",
    },
    {
      key: "moderate",
      label: "Medium",
      points: 10,
      world: "Dimension: (6, 5)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Draw a bar chart. Write <code>drawBar(k, height)</code>: with Karel facing north at the bottom of a column, drop <strong>one beeper per corner</strong> going up until the bar is <code>height</code> tall, then walk back down to the bottom. Use it to draw bars of height <strong>2, 4, 3, 1, 5</strong> on avenues 1 through 5, stepping one avenue east between bars. Karel starts facing east, so turn north first.\n<p><code>turnRight</code> and <code>turnAround</code> are provided; write any other helpers you want (a <code>moveN</code> and a <code>nextColumn</code> make the job much easier). Only the beepers are graded &mdash; Karel may finish anywhere.</p>",
      starter: "function turnRight(k) {\n  for (let i = 0; i < 3; i++) {\n    k.turnLeft();\n  }\n}\n\nfunction turnAround(k) {\n  k.turnLeft();\n  k.turnLeft();\n}\n\nfunction drawBar(k, height) {\n  \n}\n\nfunction main(k) {\n  \n}\n",
      check: ["beepers"],
      solution: "DRQcBhhEDB0RREMTQyEMBgQRTEZfERBrUkUKQhFTGVxTFQ0aRVxMVV8NHxFXQUFeTERIWBgQTWsNU0VBB0sQWARfJwQUEUQEWHkREEtrUHlvBxkLB1kfXgVBBhAeQyIBXkVYBQUYTEEXb0QNHR8fFAALIEgFBxkZDWsNUw5PGBAWQzpUDRVaTFcnHnk7VkMPTgcMDgJFCUIAVCVJGUlMQ0pTSjoWQUscF0FECQFZVlhLXFJVVw0KUw0QWFoNGk5KRUUfJ1YRS0EZSwFCFRYZGQ1rDVMYaxFvbksDXwgVGwoCDQcBUEd0AF9bDk1MDQFEEVkfSFIeZg1DFV5CFklBFhFBBUVZDUYKSwhSWUxFBhpWWEJBAFNUWkwMTwZfERBrUkVMDQhdQUVCI0gWFQQeTU0WfBFLQVIOQkAMBVQYH1onU0UcZkVERlhBHhUwAAldBgEZGQ1rDVMRFB4LJV8ZRAUFWg5FFmlTEV1ZF0g9TQpARQxIH1YDFVJITBxKSDsQFhVYAQsgHgoRQxIZAEhJbxEnaRVEXlUVRBwLQQIAHFk1XgcUHwtERkpTSjoWQVkGFw8+DANFAhkASElvTA0IXVxfQAQFWl5rTEUPAwJEGQ8+AApZS1oKOktrJxUQDw8RDUIYEQYAGwtERkpTSjoWQUZdERQeCyhIEEVDSElvTA0HAVBHdABfWw5NTFdNFnwRSw8XHRhuDB9EXVhJRlpea0xFAF8XRikAAE0HAUNHGAs8QQ0dABkYJgtBA1wFSRlMVydDU1VCVxZvEhdJB0lEHl8KYUFSCwlVFzBeXEMMQ1sOSFdvRA0SQwoWMAQeBQhfEQEfWidTRQ8JHRBuGV0eDBxNBwRYeREQUhNMBCcAHk0PAVYEQlp4GA==",
    },
    {
      key: "complex",
      label: "Difficult",
      points: 15,
      world: "Dimension: (5, 4)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Paint a four-color frame around a 5&times;4 room using a function that takes a <strong>string</strong> and a <strong>number</strong>. Write <code>paintN(k, c, n)</code>: paint the current corner with the color <code>c</code>, step forward, and repeat <code>n</code> times &mdash; so <code>paintN(k, \"Red\", 4)</code> paints four corners red and leaves Karel on the corner after them. Inside the body pass <code>c</code> straight on to <code>paintCorner</code>; don't put quotes around it.\n<p>Then, from <code>main</code>, walk the border with a <code>turnLeft()</code> between legs: the south wall <strong>Red</strong>, the east wall <strong>Blue</strong>, the north wall <strong>Green</strong>, and the west wall <strong>Yellow</strong>. The room is wider than it is tall, so the legs are not all the same length &mdash; count how many corners each side needs so that every one of the 14 border corners is painted exactly once and the middle stays blank. Karel starts at <code>(1, 1)</code> facing east. Only the paint is graded.</p>",
      starter: "function turnRight(k) {\n  for (let i = 0; i < 3; i++) {\n    k.turnLeft();\n  }\n}\n\nfunction turnAround(k) {\n  k.turnLeft();\n  k.turnLeft();\n}\n\nfunction paintN(k, c, n) {\n  \n}\n\nfunction main(k) {\n  \n}\n",
      check: ["colors"],
      solution: "DRQcBhhEDB0RREMTQyEMBgQRTEZfERBrUkUKQhFTGVxTFQ0aRVxMVV8NHxFXQUFeTERIWBgQTWsNU0VBB0sQWARfJwQUEUQEWHkREEtrUHlvBxkLB1kfXgVBBhAeQyIBXkVYBQUYTEEXb0QNHR8fFAALIEgFBxkZDWsNUw5PGBAWQzpUDRVaTFcnHnk7VkMPTgcMDgJFFEwfXx8vWg5ADQBfEV4fQVZ5RUEKChYNXl0OFVIMTBBDQwoQX0ERUwtaTAxPBl8REGtSRUwNCF1BUV8PWTAKEwIAFgUVGFBrUkVMDQhdXF9ABAVaXmtMRRknCzthBwcLD1kKHF8QWwBEHU0KRUUfJ1YRGwAbCxhjSxgdEBQzSBdHTUxRTRZ8EUsKXBEZXw0/VFZCSQRIb0FMFQVEGEUlSRlJTA8hH0RVFE0NQExaZkVERlhFHhMcKQlLF1sYCzxBDQMECAIRKgUdHUtDNRcJSA1RHRACSBZ5RUEHSxBYBF8nBBQRRARYeREQRgBEHREvRA5IDVRoDg0eChsPT1MCGQ1rUA==",
    },
    {
      key: "hard",
      label: "Hard",
      points: 20,
      world: "Dimension: (8, 4)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Draw a pyramid and come home. Seven bars, one per avenue from 1 to 7, with heights <strong>1, 2, 3, 4, 3, 2, 1</strong> &mdash; one beeper per corner, stacked. Don't write seven calls by hand: use <code>for</code> loops and compute each bar's height from the loop counter (the lesson used <code>i + 1</code> to climb; think about what expression comes back down).\n<p>When the pyramid is finished, bring Karel back to <code>(1, 1)</code> facing <strong>east</strong>. A <code>moveN</code> with the right argument gets you most of the way there.</p>\n<p>Only <code>turnRight</code> and <code>turnAround</code> are provided &mdash; write <code>drawBar</code> and everything else yourself. Beepers, Karel's final position and facing are all graded.</p>",
      starter: "function turnRight(k) {\n  for (let i = 0; i < 3; i++) {\n    k.turnLeft();\n  }\n}\n\nfunction turnAround(k) {\n  k.turnLeft();\n  k.turnLeft();\n}\n\nfunction main(k) {\n  \n}\n",
      check: ["beepers","position","direction"],
      solution: "DRQcBhhEDB0RREMTQyEMBgQRTEZfERBrUkUKQhFTGVxTFQ0aRVxMVV8NHxFXQUFeTERIWBgQTWsNU0VBB0sQWARfJwQUEUQEWHkREEtrUHlvBxkLB1kfXgVBBhAeQyIBXkVYBQUYTEEXb0QNHR8fFAALIEgFBxkZDWsNUw5PGBAWQzpUDRVaTFcnHnk7VkMPTgcMDgJFCUIAVCVJGUlMQ0pTSjoWQUscF0FECQFZVlhLXFJVVw0KUw0QWFoNGk5KRUUfJ1YRS0EZSwFCFRYZGQ1rDVMYaxFvbksDXwgVGwoCDQcBUEd0AF9bDk1MDQFEEVkfSFIeZg1DFV5CFklBFhFBBUVZDUYKSwhSWUxFBhpWWEJBAFNUWkwMTwZfERBrUkVMDQhdQUVCI0gWFQQeTU0WfBFLQVIOQkAMBVQYH1onU0UcZkVERlhBHhUwAAldBgEZGQ1rDVMRFB4LJV8ZRAUFWg5FFmlTEV1ZF0g9TQpARQxIH1YDFVJITBxKSDsQFhVYAQsgHgoRQxIZAEhJbxEnaRVEXlUVRBwLQQIAHFk1XgcUHwtERkpTSjoWQVkGFw8+DANFAhkASElvTA0IXVxfQAQFWl5rTEUPAwJEGQ8+AApZS1oKOktrJxUQDw8RDUIYEQYAGwtERkpTSjoWQUZdERQeCyhIEEVDSElvTA0FHEMQHg1IB0UITFhEHU0RAkFORVgWQxoaGx9BVnlFQUxFAF8XRikAAE0HAUMaERsWUARIb0FMRURDE0kfIh0JGUANW1oZDWsNUxhrTEUCQgQRQw0XEUxEQ04RAA1BRFNZQV9eRERdGkJBCW9MDUNTVUJXFm8SF0kHSUQeVhxLCFteZg1DUxFeUxlZMAoNGQgKBR0YUGtSRREnQ1NaHkIUXx0pBAoRTARNO0tBHwoaSC1bWhwWVgRIb0FMERFfGHAZDgcLCAUIWgo6Sw==",
    },
  ],
};

export default lesson07;
