/**
 * Assignment "lesson-09" — companion to lessons/09-returns.html (Return Values).
 *
 * GENERATED by tools/gen-lesson-assignments.js — edit the problem there and
 * regenerate; do not hand-edit the sealed solutions below. Each of the three
 * problems (simple / moderate / complex) stores its reference solution SEALED
 * (see tools/seal.js). The plaintext solutions live in the generator.
 */
export const lesson09 = {
  id: "lesson-09",
  lessonNum: 9,
  lessonSlug: "09-returns",
  lessonTitle: "Return Values",
  title: "Assignment 9 · Return Values",
  points: 50,
  problems: [
    {
      key: "simple",
      label: "Simple",
      points: 5,
      world: "Dimension: (3, 2)\nKarel: (1, 1); east\nBeeperBag: INFINITY\nBeeper: (1, 1); 1\nColor: (1, 1); Blue\nBeeper: (3, 1); 1\nBeeper: (2, 2); 1\nBeeper: (1, 2); 1\nColor: (1, 2); Blue",
      prompt: "Some corners in this 3&times;2 room hold a beeper, and some are painted <code>\"Blue\"</code> &mdash; but only a corner with <strong>both</strong> is real treasure. Write <code>isTreasure(k)</code> using nested <code>if</code>s over <code>k.cornerColorIs(\"Blue\")</code> and <code>k.beepersPresent()</code>, returning <code>true</code> only when both hold. Sweep the room &mdash; east across row 1, turn, west across row 2 &mdash; and call <code>isTreasure(k)</code> directly inside an <code>if</code> to decide whether to pick up the beeper at each corner. Leave beepers on non-treasure corners alone.",
      starter: "function isTreasure(k) {\n  \n}\n\nfunction main(k) {\n  \n}\n",
      check: ["beepers"],
      end: {"avenue":1,"street":2,"direction":"west"},
      solution: "DRQcBhhEDB0RWUU1XxYEEhkXAQUdGEsaeEVMRAVTGVsYAkIBCwQeJgtBGUMiElpHLkEWFhMZH0FWeUVBTEUNS1YZAE8QAAldBgFCYEQEXhYLFURMTQ0EVB8UAAtMWREGVAs8QQ0Ob0FMFwFZA0MFQRQEAF4GSDtNPGtLBgsCGAwLQ1ZcCggcTQcEQwg7EBYHQgFFSQAAEA0fEVZBQl5MRENPEQINQURYTkhMHm4NVhFLCBRFREQQJ0NVVxJYAQBJB0xNDR0fGwgRDi5IBgNUQh5IFnlFQUxFDwMbXh0EWkxXJ0NTTDoWQUQVRUkFFjBfE1AYFAAAREZKWhFbGBFEEA4jCQAUSAQZQlp4RUxGTQdEQlgtSBURSUVebg1WWkUMHRMJBUpIOxAWCgMHEBMCKQFLAhlCWnhFTEsMAREYWgRZUwxBUUVUFlZYS11SV1cNClgaGRYaJ1NFQUwMAg1eWBg1AAANXhYBVBhdSARTDk8cDAdGNFQOERcXRARYeREQFkFGXQgOGgBMBE07S0EPb0wNChURGF8SeQEAAB8QFkheWkJIUg5CXQoQWnJTBF0WF0lFXm5Q",
    },
    {
      key: "moderate",
      label: "Moderate",
      points: 10,
      world: "Dimension: (8, 8)\nKarel: (1, 1); east\nBeeperBag: 0\nBeeper: (2, 1); 3\nBeeper: (3, 1); 5\nBeeper: (5, 3); 6\nBeeper: (6, 3); 2\nBeeper: (1, 5); 2\nBeeper: (2, 5); 4\nBeeper: (6, 7); 5\nBeeper: (7, 7); 1",
      prompt: "An 8&times;8 room hides four pairs of beeper piles, each pair sitting on two corners immediately next to each other along a row. Karel starts at <code>(1, 1)</code> facing east, and the travel between pairs is already wired up in <code>main</code> below &mdash; your job is the two functions it calls at each stop.\n<p>Write <code>beepersInLargerPile(k)</code>, called while Karel stands on a pair's <strong>left-hand corner, facing east</strong> toward its right-hand partner: pick up and count the pile under Karel, move forward and do the same to the neighboring pile, then <code>return</code> the string <code>\"right\"</code> or <code>\"left\"</code> naming whichever pile was bigger. Leave Karel back where it started, facing the same way.</p>\n<p>Then write <code>markWinner(k, winner)</code>, which takes that return value and paints <code>\"Red\"</code> onto whichever corner of the pair actually held more beepers &mdash; again leaving Karel back on the pair's left-hand corner, facing east, so the next pair can be found the same way.</p>",
      starter: "function beepersInLargerPile(k) {\n  let leftCount = 0;\n  let rightCount = 0;\n  \n}\n\nfunction markWinner(k, winner) {\n  \n}\n\nfunction turnRight(k) {\n  k.turnLeft();\n  k.turnLeft();\n  k.turnLeft();\n}\n\nfunction turnAround(k) {\n  k.turnLeft();\n  k.turnLeft();\n}\n\nfunction main(k) {\n  k.move();\n  markWinner(k, beepersInLargerPile(k));\n\n  for (let i = 0; i < 3; i++) k.move();\n  k.turnLeft();\n  k.move();\n  k.move();\n  turnRight(k);\n  markWinner(k, beepersInLargerPile(k));\n\n  k.turnLeft();\n  k.move();\n  k.move();\n  k.turnLeft();\n  for (let i = 0; i < 4; i++) k.move();\n  turnRight(k);\n  turnRight(k);\n  markWinner(k, beepersInLargerPile(k));\n\n  k.turnLeft();\n  k.move();\n  k.move();\n  turnRight(k);\n  for (let i = 0; i < 5; i++) k.move();\n  markWinner(k, beepersInLargerPile(k));\n}\n",
      check: ["colors"],
      solution: "DRQcBhhEDB0RREMTQyEMBgQRTEZfERBrUkUHAxcGQ156BEsHTUhXb0QNHR8fFAALIEgFBxkZDWsNUw5PGBAWQzpUDRVaTFcnHnk7VkMPTgcMDgJFEFgEXyoTHRACSUsYGBBNaw1TDk8YEBZDOlQNFVpMVydDU1oeQhRfHSkEChFMBE07Fmt4AxlDAAdYX1hBTxYAEQkXF2QYfQoTFQAefQofVBhdSA0Ib0FMCQFZVl0OBwYmA1gNBxENFlEWeUVBAAAQDQRYDAkGJgNYDQcRDRZRFnlvQUwSDEQaVEtJGUsOSAYDVEJFMV8WFgQCEUwEXxEQa1JFTA0IXUFZVQpvFgARCRdMBE07S0FSRQBIBQdyX0MPWVhOWmZFRFB8EUsKXAgDWwZbGAs8QQ0EDQgAAEQFHR8JBBcVCV8QI0NVRQRDB01IRUUfJ1YRS0EZSxxEABhzVVMRSAFNSFdvRA1WERkIFQ0YbgwGX0QdShZ5RUERb0QNAkQZDzMXA1gNFxlbH1onU0UKQggLWxMZQlp4RUxZFgFfcUQOWB0BSQdMXyd8EUsIFEVEXwoUWUR1DlgdEUFSRQhIEEUoDgcLGARDAVREQxNDU0cTBQIMWVQKYUFSFwlZFgFfEBQNSBURQ1dvGSd8Vx4PEREFQg1TXFFECnoaCw8JF0xGWhEcCBwLCV9KU0o6FkFEFUVJGwwKQxNDS1xPWEwPERpWWEJDBFMea0xFRA0dHwYOBABEBFh5ERAWQUZdFQAFCxBuGUMFBABNTn8GFxMZDWsNU0VBGBAWQzdDBBQcAURGSkg7EBZBDRhLDAMTAQVfCmFBUkVMWRYBX3FEDlgdAUkHTF8nVhEWQRcJH0hDCDsQFkENGEsRDQwKWTVeGQ8XF0QPMRZVEh9aJ1NFHGYYbicQRAUCBgwDQ0MeUFlYSUZaRRpmRURGWFwEFxdNRRZpUxFdVxNGJAwPAgAWBR0dSwMXABxIEQB4XnoAXxQAEzwMCEheWkJISW9mDUMVXkIWSUEWEUEFRVkNRgpLCFJZTB5YU1gbHUgNGEsMAxMBBV8KYUFSDkJZFgFffFMHWVtMWmZFREZYXAQXF01FFmlTEVsYDEIFAElFXm4NVkUeExw3BUoLBxlbH1onU0UMDRcPeh9fBQQATQcBQxFUVUYEXwAsDyAEFkoTQzsIHgBERkpaCjo8QQ0YSxUZFwphE1cfSVteZg1DGB9dWRdIW0xaZkVERlhcBBcXTUUWaVMRWxgVWAELLQkDEAVfCmFBUgMDX0NbXVVCQURTWEFcXkREVg1LVUlFBQZIWhFbGAxCBQBJRV5uDVZFHhMcNwVKCwcZWx9aJ1NFFRkXCn8fVgMVWg5FFmlTEV1XE0YkDA8CABYFHR1LAxcAHEgRAHheegBfFAATPAwISF5aQkhJb2YNQxgfREMTQz8ABxhNTRZ8EUsKXAgDWwZbGAs8QQ0YSwwDEwEFXwphQVIRGV8NIVhXXhUFGExaZkVESxlDS0keABgNClMMEAZaDRpFXUxQXw0fGkBIUg5CQAwFVBgfWidTRQwNFw96H18FBABNBwFDEVRVRgRfACwPIAQWShNDOwgeAERGSloKOks=",
    },
    {
      key: "complex",
      label: "Complex",
      points: 15,
      world: "Dimension: (4, 3)\nKarel: (1, 1); east\nBeeperBag: INFINITY\nColor: (1, 1); Green\nColor: (3, 1); Green\nColor: (2, 2); Green\nColor: (4, 3); Green",
      prompt: "A 4&times;3 room has a few corners painted <code>\"Green\"</code>, scattered with no pattern. Write <code>countGreen(k)</code> that sweeps the <strong>entire grid</strong> &mdash; all three rows, in a back-and-forth snake pattern (east, turn up, west, turn up, east) &mdash; and <code>return</code>s the total number of green corners. Capture that number in a variable, and once the sweep ends, drop that many beepers on the final corner.",
      starter: "function countGreen(k) {\n  let count = 0;\n  \n  return count;\n}\n\nfunction main(k) {\n  \n}\n",
      check: ["beepers","position"],
      end: {"avenue":4,"street":3,"direction":"east"},
      solution: "DRQcBhhEDB0RREMTQyEMBgQRTEZfERBrUkUHAxcGQ156BEsHTUhXb0QNHR8fFAALIEgFBxkZDWsNUw5PGBAWQzpUDRVaTFcnHnk7VkMPTgcMDgJFB0IDXx8mAAAJQ0sYGBBNaw1TCQQYRQdCA18fQU9FXBZpUxFWWRMNWwkEGEUWQgERVkFCXkxfDAQRDBZSFlMXDhtOTwRWSmFBUkVMRAVTGVsYAkIBCwQeJgtBGUMiElpHK18GFl8SH0gNEAoUAhFPBk07S0FSRQpCEVMZXFMVDRAKDUxYRB1NEQgOHkVQDVBIEVNZDQZYTEEXb0QNVhFLQRlLAUIVFhkZDWsNU0VBTEUNS1YZAE8RCh5DBgFyX1oOXzoWSU4iFkgTX0lIW0UPQhYdRRsdWidTRUFMGG4NVhFLCBRFRF8MBBEMFlMEUx5rTEVEDVYRAgdSTQcDBRJSWVgGaBIWFURMTQ0NO0tBUkVMDUNTWh5CFF8dKQQKEUwETTtLQVJFTA1DU1oeWw5bFk1IV29EDVYRS0FSRQcDFwZDXnoESwdNSFdvRA1WEUtBD0UJQRAWEUs8QQ1TRUFMRURZA0MFMxsCBFlLGBgLPEENU0VBTEVERlhcBBcXTUUWaVMREBZBDVNFFRkXCn8fVgMVWg5FFmlTERAWQQ0Ob0FMRURQfBFLHHhFTF8GB0RCWEFOHBAPGF5uUHw7DRQcBhhEDB0RXVcIQ1sOSEwebg1WUgQPARFMWQwHUFwWXA0QChQCESNfE1QFSRlMVydDU1dfREEFHwAVTAxEEFYBUEEbRVANFxxFUVpaDRpOSkVFHydWEUtBGUscWBcxVFVGBF9bTFpmRURQfEw=",
    },
    {
      key: "complex2",
      label: "Complex II",
      points: 20,
      world: "Dimension: (5, 3)\nKarel: (1, 1); east\nBeeperBag: INFINITY\nBeeper: (1, 1); 1\nColor: (1, 1); Orange\nBeeper: (3, 1); 1\nColor: (3, 1); Orange\nBeeper: (5, 2); 1\nColor: (5, 2); Orange\nBeeper: (2, 2); 1\nBeeper: (1, 3); 1\nColor: (1, 3); Orange\nColor: (4, 3); Orange",
      prompt: "A 5&times;3 room mixes beepers and <code>\"Orange\"</code> paint &mdash; some corners have one, some the other, some both, most neither. Only a corner with <strong>both</strong> counts as marked. Write <code>isMarked(k)</code> with nested <code>if</code>s over beeper-presence and color, then a helper <code>collectMarked(k)</code> that sweeps <strong>one row</strong>: it picks up the beeper at every marked corner it passes and <code>return</code>s how many it collected. Call <code>collectMarked(k)</code> once per row &mdash; three rows, in a back-and-forth snake pattern &mdash; adding each row's return value into a running total. When the sweep is done, drop that many beepers on the final corner.",
      starter: "function isMarked(k) {\n  \n}\n\nfunction collectMarked(k) {\n  let count = 0;\n  \n  return count;\n}\n\nfunction main(k) {\n  let total = 0;\n  \n}\n",
      check: ["beepers","position"],
      end: {"avenue":5,"street":3,"direction":"east"},
      solution: "DRQcBhhEDB0RWUUsTAEOBAhNDwRWSmFBUgwKDUsYH1JTBF0WFxI8FwFeE18fSVtMTFZpUxEQFghLU00KQgYLXxhUGSIdCQNfKgAZEnkTTB0CBE5MTQ0EVB8UAAtMWREGVAs8QQ0Ob0FMFwFZA0MFQRQEAF4GSDtNPGtLBgsCGAwLQ1ZSBA0eAA9ZLhJDW1MFBRhMQRdvRA0aVB9BEQoZQxdTDBAGWidTRQgKRUxEBXwKExkACAUIWhgQTWsNU0VBB0sURBVaKQQXFQlfS1oKOhZBDVMGDhkLEAZdCmFBUhhmDUMVXkIWSUEWEUEFRVkNRgpLCFJZTBlYU1gbHUgNCG9BTEVERlhcBBcXTUUWaVMREBYIS1NNCB8oBV8dVA9JGUxFDRh5ERAWQQ1TDk8cDAdGNFQOERcXRARYeREQFkENUwYOGQsQBl0KYUFSRUxQaVMRTTxBDQEAFRkXCg0VXh4PBl5mUGl5V0VYAlkaCg9MERFfGGMCBhoRREZKU0o6FkFGXREUHgsoSBBFQ0hJb0wNCF1FRUQPYRYDFURMXydWEQBPBhAeQy8WV0QeSBZ5GGtmAxFDFUUCDhxFAUwKHRlbH0FWeUVBAAAQDQJeHwAeRVENU0g7EBYVQgcEDUxYRFkZRQoNUk5MTgwfXVVVFWASFwoJAUxGXwphQVIOQlkWAV98UwdZW0xaZkVERlhcBBcXTUUWaVMRWxgVWAELLQkDEAVfCmFBUhEDWQIfEQ0WFUIHBA1MTkROGV0HBBERIUwRGFRUHgoESG9BTBERXxhjAgYaEURGSkg7EBYKAx4KFwlNTRZ8EUsVBxcCfwoUWUQeCgRIb0FMEQtZF11LXFIRA1kCHxEbFgJCHwkEDxEpTARaDgVaDkUWaVMRVlkTDVsJBBhFDQ1LEVtaUgxMEUMHXkRXDRZTDEpHTERWfBFLQVIOQl0WB3NVUxFIAU1IV29EDQs7Fg==",
    },
  ],
};

export default lesson09;
