/**
 * Assignment "lesson-04" — companion to lessons/04-for-loops.html (The for Loop).
 *
 * GENERATED by tools/gen-lesson-assignments.js — edit the problem there and
 * regenerate; do not hand-edit the sealed solutions below. Each of the three
 * problems (simple / moderate / complex) stores its reference solution SEALED
 * (see tools/seal.js). The plaintext solutions live in the generator.
 */
export const lesson04 = {
  id: "lesson-04",
  lessonNum: 4,
  lessonSlug: "04-for-loops",
  lessonTitle: "The for Loop",
  title: "Assignment 4 · The for Loop",
  points: 30,
  problems: [
    {
      key: "simple",
      label: "Simple",
      points: 5,
      world: "Dimension: (6, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Use a <code>for</code> loop to move east five times, ending on <code>(6, 1)</code>.",
      starter: "function main(k) {\n  \n}\n",
      check: ["position"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WVwQTUk0ASBdTWBALQR1IRQhMWUQYTRECSllMTFZpUxEQFgoDHgoXCU1NFnwRSxx4GA==",
    },
    {
      key: "moderate",
      label: "Moderate",
      points: 10,
      world: "Dimension: (4, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Use a <code>for</code> loop to drop a beeper on every one of the four corners, finishing on <code>(4, 1)</code>.",
      starter: "function main(k) {\n  \n}\n",
      check: ["beepers","position"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WVwQTUk0ASBdTWBALQR1IRQhMWUQeTRECSllMTFZpUxEQFgoDAxAVLgABXRNDQ0hJb0wNQ1NaHlsOWxZNSFdvRA0LO0tBGUscWBcxVFVGBF9bTFpmGA==",
    },
    {
      key: "complex",
      label: "Complex",
      points: 15,
      world: "Dimension: (5, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Drop a beeper on all five corners, then turn around and return to <code>(1, 1)</code>, finishing there facing west.",
      starter: "function main(k) {\n  \n}\n",
      check: ["beepers","position","direction"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WVwQTUk0ASBdTWBALQR1IRQhMWUQZTRECSllMTFZpUxEQFgoDAxAVLgABXRNDQ0hJb0wNQ1NaHlsOWxZNSFdvRA0LO0tBGUscWBcxVFVGBF9bTFpmRURGWEUeExwpCUsXWxgLPEENGEsVGRcKYRNXH0lbXmYNQxVeQhZJQRYRQQVFWQ1GCksIUllMGVhTWBsdSA0Ib0FMRURGWFwEFxdNRRZpUxFNPBw=",
    },
  ],
};

export default lesson04;
