/**
 * Assignment "lesson-08" — companion to lessons/08-variables.html (Variables).
 *
 * GENERATED by tools/gen-lesson-assignments.js — edit the problem there and
 * regenerate; do not hand-edit the sealed solutions below. Each of the three
 * problems (simple / moderate / complex) stores its reference solution SEALED
 * (see tools/seal.js). The plaintext solutions live in the generator.
 */
export const lesson08 = {
  id: "lesson-08",
  lessonNum: 8,
  lessonSlug: "08-variables",
  lessonTitle: "Variables",
  title: "Assignment 8 · Variables",
  points: 50,
  problems: [
    {
      key: "simple",
      label: "Easy",
      points: 5,
      world: "Dimension: (5, 7)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Build an <strong>L with two equal arms</strong>. Karel starts at <code>(1, 1)</code> facing east and doesn't know how wide the room is. Put a beeper on every corner from the start to the east wall, then turn north and lay a second arm of beepers exactly as long as the first (the corner beeper is shared by both arms). The room is taller than it is wide, so the north wall won't tell Karel where to stop &mdash; a variable has to. Beepers and Karel's final position are graded.",
      starter: "function main(k) {\n  \n}\n",
      check: ["beepers","position"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WXQ4VUhYYSBMAEQ0WURZ5RUEHSxRYAnMOBAIAHgVKSDsQFhZFGgkETE0PAxBDBA8GLB9uDxZQQh5IBFMea0xFRA0dHwYOBABEBFh5ERAWQUZdFRQYJwFIBlQZSVteZg1DUxFDQgRdAE5KV29EDQs7S0EZSxhYER19VVAVBVpea0xFAkIEEUMNFxFMRENOEQANQURTWUEfEQFdBQpLCFlORQ0YeREQFkFGXQgOGgBMBE07S0FSRQcDEwZFclMEXRYXSUVebg1WTGEc",
    },
    {
      key: "moderate",
      label: "Medium",
      points: 10,
      world: "Dimension: (5, 4)\nKarel: (1, 1); east\nBeeperBag: INFINITY\nBeeper: (2, 1); 2\nBeeper: (4, 1); 1\nBeeper: (5, 1); 1\nBeeper: (1, 2); 1\nBeeper: (3, 2); 2\nBeeper: (2, 4); 1\nBeeper: (3, 4); 1\nBeeper: (4, 4); 1\nBeeper: (5, 4); 2",
      prompt: "Every row of this room has beepers scattered along it, some in piles. For <strong>each row</strong>, gather all of that row's beepers into a single pile on the row's west-end corner (avenue 1). A row with no beepers stays empty. Karel's bag is unlimited, so it can't just empty the bag &mdash; it has to know how many it picked up. Use sensing, not fixed counts, to cross each row and to decide whether there's another row above. Only the beepers are graded.",
      starter: "function main(k) {\n  \n}\n",
      check: ["beepers"],
      solution: "DRQcBhhEDB0RREMTQyEMBgQRTEZfERBrUkUHAxcGQ156BEsHTUhXb0QNHR8fFAALIEgFBxkZDWsNUw5PGBAWQzpUDRVaTFcnHnk7VkMPTgcMDgJFEFgEXyoTHRACSUsYGBBNaw1TDk8YEBZDOlQNFVpMVydDU1oeQhRfHSkEChFMBE07Fmt4AxlDAAdYX1hBQBIMD0QOTQ0NO0tBHgAYDQAbVFNdCEMURVxMERZYEwphQVISBEQPFhEYVQlIEA4IAgJNDQ07S0FSRQBIF1NSX0MPWVNYQVxebg1WEUsWGgwASENbWh5UBEgDABMfNRZIBVQFFVpMRQ0YeREQFkENUw5PHAwHRjRUDhEXF0QEWHkREBZBDVMGDhkLEAZdCmFBUkVMUGlTERAWFkUaCQRMTQ8DEEMEDwYsH24PFlBCHkgEUx5rTEVEDVYRAE8fChpIS1oKOhZBDVNFQRsNDUETEUMKXAcJSBMWQ0NmE0gAAA8YTU0EVkphQVJFTA1DUxFbGBFEEA4jCQAUSAQZQlp4RUwNQ1MREBYCQgYLFUdOXydWEUtBUkURJ0NTERBLaw1TRUEYEBZDN0MEFBwBREZKSDsQFkENBA0IAABEBR0fDRMdCxhkEDBdVVcTBVpMQRdvRA1WEUtBGUsBQhUWGRkNaw1TRUERb0QNVhENDgBFREEGBxFZFlwNQ15BBUVYDRVeHg8GXkxESFgYEE1rDVNFQUxFDwMGRB8jFwAcSBFbGAs8QQ1TRRxmRUQNVkUeExw3BUoLBxlbH1onU0VBTAwCDV5aRQcACgJZKgByXFMAX1tMSEwebg1WEUtBUg5CQAwFVBgfWidTRUFMRURZA0MFMxsCBFlLGBgLPEENU0UcTAAIXhMREGtSRUwNQ1NSWFMCRhoLBkxYREsXXRgESW9MDUNTTDoWQVB5GA==",
    },
    {
      key: "complex",
      label: "Complex",
      points: 15,
      world: "Dimension: (5, 4)\nKarel: (1, 1); east\nBeeperBag: INFINITY\nColor: (1, 1); Red\nColor: (3, 1); Red\nColor: (5, 1); Green\nColor: (2, 2); Green\nColor: (4, 2); Green\nColor: (5, 2); Red\nColor: (2, 3); Red\nColor: (4, 3); Green\nColor: (1, 4); Red\nColor: (3, 4); Green\nColor: (5, 4); Green",
      prompt: "Some corners in each row are painted <code>\"Red\"</code> or <code>\"Green\"</code>; the rest are blank. For <strong>each row</strong>, decide the row's majority color and paint every <em>blank</em> corner in that row with it &mdash; leave already-painted corners alone. If a row has the same number of red and green corners, fill its blanks with <code>\"Yellow\"</code> instead. Keep the chosen color in a <strong>string variable</strong> and pass it to a helper that does the painting. Only the paint is graded.",
      starter: "function main(k) {\n  \n}\n",
      check: ["colors"],
      solution: "DRQcBhhEDB0RREMTQyEMBgQRTEZfERBrUkUHAxcGQ156BEsHTUhXb0QNHR8fFAALIEgFBxkZDWsNUw5PGBAWQzpUDRVaTFcnHnk7VkMPTgcMDgJFEFgEXyoTHRACSUsYGBBNaw1TDk8YEBZDOlQNFVpMVydDU1oeQhRfHSkEChFMBE07Fmt4AxlDAAdYX1hBSxoJDS4JBUMdGQBNUgYDQQwBGBBNaw1TDAdMTQ8DFV4ZDxcXL0IPHEN5RUkPIQAFTkxNDQ07S0FSRUMCQxJdQlMASQpFEQ0MClkTVUtMUgkJTBUWEVlCaw1TGEEJCRdIVlgNQVoOQk4MAV9VRCJCHwoTJRZMDzFDDgQcR0UEQwg7EBZBDVxKQQ0JFkgXVRJBAgQFQxcWVRAbQUEWBBcJRQ1ZfBFLHFIAAF4GU0o6FkENUw5PHAQNQwJyBBMcAB4FABxdX0RIFnlFQRFvGSd8Vx4PEREFQg1TXFFfDwUYTEEXb0QNGlQfQRENCU4IGl9XFlwNBxcUCV5uDVZGAwgeAEwFABtUU10IQxRMQRdvRA1WEQcEBkUeSAcwXkVYFQ1ORVFXb0QNVhEHBAZFC18GFl9zWRRDB0VcTFVfJ1YRS0EbA0wFCF1SX0QPSAEmDgAKFmQFGUkzFwFOBEpTQ1VSIkIGCxVHTl8nVhFLQRsDTAUIXVJfRA9IASYOAAoWZAUZSSYAAAlDQVoYEFETSBYLIgMQClldGlBrUkVMDRQbWFxTQQUYSwceCgpZP0IoDRcEHgVKWhFLPEENU0VBTA5KQBlHDklbXmYNQ1MREBYIS1NNCkIGC18YVBkiHQkDXyoAGRJkBElRTEhMFwFJNV4eDwZORxZpUxEQFkENGgNBRA5KThlDBQQAJgNBDAF4Qx5DagEABAJHTQRWVhkEFwsvQhYdRRsdWidTRUFMGG4NVhFLDRcRTFoKHV9VREEQU0c4CQkIQgETUGtSRUwNChURGEQESTAKFAIRRBNWVhkEFwsvQhYdRRkWGidTRUFMRURaH18FBABFUQ1BIVRUFFonU0VBTBhESBpCDkEbA0wFBAFUVVgiQgYLFUxbRF8TVSgOBwsYBEMIOxAWQQ1TRRYFCwpIBBFWQVAiHkgGHRMLPEENU0UcZkVEDVZFHhMcJB5CFh1VGF1IFnlFQUxFAkQaXSkNEwsHBQhfEUdfD0MWF0hXb0QNVhEcCRsJCQ1LGB9WRA5DBywSLwkBTAQZQkhSHmYNQ1MREBYKAx4KFwlNTRZ8EUtBUkVMSwofXXJaAEMYTQpARRNEGF8OE1teZg1DUxFNPEENU0UVGRcKfx9WAxVaDkUWaVMREBYIS1NNCkIDFkIYRSISMQkJTBFbGBkWGidTRUFMRURGWFwEFxdNRRZpUxEQFkENBxATAjcNSh5FQwpbXmYNQ1MRTRYEQQAAQRdvRA1WEUtBEQ0JTggaX1cWXA0VBA0fAF8nVhFLQQ9vTA0eeUw=",
    },
    {
      key: "hard",
      label: "Hard",
      points: 20,
      world: "Dimension: (6, 5)\nKarel: (1, 1); east\nBeeperBag: INFINITY\nBeeper: (2, 1); 1\nBeeper: (5, 1); 1\nBeeper: (1, 2); 1\nBeeper: (3, 2); 1\nBeeper: (6, 2); 1\nBeeper: (2, 3); 1\nBeeper: (3, 3); 1\nBeeper: (4, 3); 1\nBeeper: (5, 3); 1\nBeeper: (6, 3); 1\nBeeper: (1, 4); 1\nBeeper: (2, 4); 1\nBeeper: (4, 4); 1\nBeeper: (6, 4); 1\nBeeper: (3, 5); 1",
      prompt: "Single beepers are scattered across a 6&times;5 room. Find the row that holds the <strong>most</strong> beepers (there are no ties), then pick up every beeper in that row and put them all in one pile on the row's west-end corner. Every other row must be left untouched, and Karel must finish standing on the new pile. Karel doesn't know the size of the room or how many beepers any row holds in advance; it can't tell which row wins until it has looked at all of them. Beepers and Karel's final position are graded.",
      starter: "function main(k) {\n  \n}\n",
      check: ["beepers","position"],
      solution: "DRQcBhhEDB0RREMTQyEMBgQRTEZfERBrUkUHAxcGQ156BEsHTUhXb0QNHR8fFAALIEgFBxkZDWsNUw5PGBAWQzpUDRVaTFcnHnk7VkMPTgcMDgJFEFgEXyoTHRACSUsYGBBNaw1TDk8YEBZDOlQNFVpMVydDU1oeQhRfHSkEChFMBE07Fmt4AxlDAAdYX1hBQBIMD0QOTQ0NO0tBHgAYDREcRhALQRxIb0FMCQFZVlMOEgY3A1pDThEBDWsNUwkEGEUGSAVFKA4HCxgNXlMBCzxBDR8AFUwGDEgVWgIPFUVRDRcBRFUNaw1TEgkFCQENXlIDBBEOBUMEWhFLPEENU0UNCRFEThlEBRVSWEwdWHkREBZBRBVFSQdLBkgTQQ4TATUeSBAWX0QeSARTBg4ZCxAGXQphQVJFTFoLGl1VFklGXQMTAwsQZAVyBwQTF0QESlNKOhZBDVNFQQdLCUIAVENISW9MDUNTERBfBw1bDk8OAAFdE0MYMQAAH0gNBxkZH0FOHBAPGE5PFnwRS0FSGGYNQ1MRWVBBBRAKFAIRRBNWUw4SBiYDWA0HGBBNaw1TRUFMRQZIBUUoDgcLGA1eU1JfQw9ZSG9BTEVEDVZTDhIGNwNaQ04RQlkWFnlFQUxFGSdWEUtBBhAeQyIBXkVYBQUYTFpmRUQNVkYDCB4ATAUIXVdCWQ9ZOhYiAAAFX14YQkEJb0wNQ1MREF1PQBwTBERMXydWEUtBD29MDUNTRUVED38aAgkYTQ8ETTtLQVJFBUtDW1oeUBNCHREoHyYISBdDQ0hbRRcnQ1MREBZBRl0IDhoATARNO0tBUkVMDRcGQ15kCEobEUkHTF8nVhFLQVJFHkIUWBoLPEENU0UcTAAIXhMREGtSRUwNQ1NSWFMCRhoLBkxYREsXXRgESW9MDUNTTDoWQVB5RUEYEBZDN0MEFBwBREZKSDsQFgdCAUVJAAAQDR8RVkFCXkxEQ08RQlkWDV5FAwkWEH8ZRlBBG05HBEMIOxAWQQ0YSwwDEwEFXwphQVIYZg1DGB9EQxNDPwAHGE1NFnwRSwgURURGTRFUVUYEXwA1EwkWAUMCGUJIUg5CXQoQWnJTBF0WF0lFXm4NVkYDCB4ATAUIXVdCWQ9ZOhYiAAAFX14YQkEJb0wNQ1NaHlsOWxZNSFdvRA1WEQIHUk0HAwEWVEBTE14jFwQfAApZXhhCQRlLHEQAGHNVUxFIAU1IV29EDQs7S0EGEB5DIgFeRVgFBRhMWmZFRFoeWAcEUk0HAwUBXl5CKF4wCQQNF0wEXxEQa1JFTA0IXVxfQAQFWl5rTEUZJ1YRDQ4ARURBBgcRWRZcDUNeQQVFWA0UVBgVMQoZQxdIEVkdSgRTHmtMRUQNHR8bFAYnCUgTFkMYH1onU0UcZhg=",
    },
  ],
};

export default lesson08;
