/**
 * Assignment "lesson-09" — companion to lessons/09-booleans-return.html (Return Values & Logic).
 *
 * GENERATED by tools/gen-lesson-assignments.js — edit the problem there and
 * regenerate; do not hand-edit the sealed solutions below. Each of the three
 * problems (simple / moderate / complex) stores its reference solution SEALED
 * (see tools/seal.js). The plaintext solutions live in the generator.
 */
export const lesson09 = {
  id: "lesson-09",
  lessonNum: 9,
  lessonSlug: "09-booleans-return",
  lessonTitle: "Return Values & Logic",
  title: "Assignment 9 · Return Values & Logic",
  points: 30,
  problems: [
    {
      key: "simple",
      label: "Simple",
      points: 5,
      world: "Dimension: (1, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY\nBeeper: (1, 1); 1",
      prompt: "Write a boolean-returning helper <code>hasBeeper(k)</code> that returns whether a beeper is present. Use it in an <code>if</code> to pick the beeper up.",
      starter: "function hasBeeper(k) {\n  \n}\n\nfunction main(k) {\n  \n}\n",
      check: ["beepers"],
      solution: "DRQcBhhEDB0RWFcSbxYAEQkXTEZfERBrUkUeSBcGQ14WCgMRAAQcABZeJkMOEhcLGAVKSDtNPGtLBgsCGAwLQ1ZcCggcTQcEQwg7EBYIS1NNCQ0WJkgTQQ4TWg5FBEMYH0BfAkYxAAQcABYFXwphHA==",
    },
    {
      key: "moderate",
      label: "Moderate",
      points: 10,
      world: "Dimension: (3, 1)\nKarel: (1, 1); east\nBeeperBag: 0\nBeeper: (1, 1); 1\nBeeper: (2, 1); 1",
      prompt: "Use the logical AND (<code>&&</code>): keep picking and moving <strong>while the front is clear AND a beeper is present</strong>. Karel should stop when either becomes false.",
      starter: "function main(k) {\n  \n}\n",
      check: ["beepers","position"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WRgMIHgBMBQhdV0JZD1k6FiIAAAVfXhhLR1RFBwMBFlRAUxNeIxcEHwAKWV4YQkEJb0wNQ1NaHkYIThgnBAkVAV9eGFBrUkVMDQhdXF9ABAVaXmtMRRknCw==",
    },
    {
      key: "complex",
      label: "Complex",
      points: 15,
      world: "Dimension: (4, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY\nBeeper: (2, 1); 1",
      prompt: "Write <code>shouldPaint(k)</code> returning <code>true</code> when the corner has a beeper <strong>OR</strong> is the last corner (front blocked). Walk all four corners and paint <code>\"Green\"</code> wherever it returns true.",
      starter: "function shouldPaint(k) {\n  \n}\n\nfunction main(k) {\n  \n}\n",
      check: ["colors","position"],
      solution: "DRQcBhhEDB0RQ14OWB8BMQ0MClleWkJBCW9MDREWRUVEDw0YSwMJABRIBEI7ExcWCUMXWxgQSh0NUg5PChcLQwJ4GCIeAA1fS1oKOktrJxUQDw8RDUIYEQYAGwtERkpTSjoWQUscF0FECQFZVlhLXFJVVw0KUw0QBVoNGk5KRUUfJ1YRS0EbA0wFEBteRVoFfRIMDxhNDwRfEQBPAgQFQxcwXkJYBF9bRyYeAAFDVBhQa1JFTA0IXVxfQAQFWl5rTEUZJ1YRAgdSTR9FDAZdVGYARB0RSQdMTQ0dHxsAGwsYbgwBX1VESQ80FwQJC0YETTsW",
    },
  ],
};

export default lesson09;
