/**
 * Assignment "lesson-08" — companion to lessons/08-variables.html (Variables).
 *
 * GENERATED by tools/gen-lesson-assignments.js — edit the problem there and
 * regenerate; do not hand-edit the sealed solutions below. Each of the three
 * problems (simple / moderate / complex) stores its reference solution SEALED
 * (see tools/seal.js). The plaintext solutions live in the generator.
 */
export const lesson08 = {
  id: "lesson-08",
  lessonNum: 8,
  lessonSlug: "08-variables",
  lessonTitle: "Variables",
  title: "Assignment 8 · Variables",
  points: 30,
  problems: [
    {
      key: "simple",
      label: "Simple",
      points: 5,
      world: "Dimension: (5, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Store the number of steps in a variable — <code>let steps = 4;</code> — then use it to move that many times, ending on <code>(5, 1)</code>.",
      starter: "function main(k) {\n  let steps = 4;\n  \n}\n",
      check: ["position"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WXQ4VUhYYSBMAEQ0WVRZ5RUEKChYNXl0OFVIMTBBDQwoQX0ERUxYVCRUXFlZYQEpbRQcDDhxHVR5IFnkY",
    },
    {
      key: "moderate",
      label: "Moderate",
      points: 10,
      world: "Dimension: (4, 1)\nKarel: (1, 1); east\nBeeperBag: 0\nBeeper: (1, 1); 1\nBeeper: (2, 1); 1\nBeeper: (3, 1); 1",
      prompt: "Keep a running <code>count</code> in a variable. Walk east across all four corners, picking up each beeper and counting it. On the last corner, drop that many beepers back down.",
      starter: "function main(k) {\n  let count = 0;\n  \n}\n",
      check: ["beepers","position"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WXQ4VUgYDWA0HEQ0WURZ5RUEKChYNXl0OFVIMTBBDQwoQX0ERU1ZaTAxPBl8REGtSRUwNChURGF1PTxYAEQkXF30EVBgEHBFEBEpTShBdT10aBgouAAFdE0NDSElFD0IWHUUbHVoNDm9BTEVERlhcBBcXTUUWaVMRTTxBDRoDQUQOSk8TVBsEABY8XwYAVF5CSQRaRRpMDkpdH1IAIxcAHEgRWxgLFgJCBgsVR05fDQs7S0EUCh4NSx9URBYIDU5FUVdFDQ1KEQgOBwsYFkMaGhsfQUZdFRQYJwFIBlQZSVteZlA=",
    },
    {
      key: "complex",
      label: "Complex",
      points: 15,
      world: "Dimension: (4, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Build a growing staircase of beepers: put 1 beeper on corner 1, 2 on corner 2, 3 on corner 3, and 4 on corner 4. Use a counter variable for how many to drop.",
      starter: "function main(k) {\n  \n}\n",
      check: ["beepers","position"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WVwQTUk0ASBdTWBALQRxIRQhMWVkNQgpLCFlORQ0YeREQFkFLHBdBRAkBWVZbS1xSVVcNCVMNEF9aDRlOSkVFDwMGRB8jFwAcSBFbGAs8QQ1TRQgKRUxEVg1LVVtFBwMOHEdVHkgWeUVBEW8Z",
    },
  ],
};

export default lesson08;
