/**
 * Assignment "lesson-06" — companion to lessons/06-if-else.html (if / else).
 *
 * GENERATED by tools/gen-lesson-assignments.js — edit the problem there and
 * regenerate; do not hand-edit the sealed solutions below. Each of the three
 * problems (simple / moderate / complex) stores its reference solution SEALED
 * (see tools/seal.js). The plaintext solutions live in the generator.
 */
export const lesson06 = {
  id: "lesson-06",
  lessonNum: 6,
  lessonSlug: "06-if-else",
  lessonTitle: "if / else",
  title: "Assignment 6 · if / else",
  points: 30,
  problems: [
    {
      key: "simple",
      label: "Simple",
      points: 5,
      world: "Dimension: (1, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Using <code>if</code> / <code>else</code>: if a beeper is present, pick it up; otherwise, put one down. (This corner is empty, so Karel should leave a beeper.)",
      starter: "function main(k) {\n  \n}\n",
      check: ["beepers"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WWA1BWg5CTwYWQVVEEn0BABIJCxAFXxhLGnhFTA1DGB9AXwJGMQAEHAAWBV8KYUFSGExIDwBUEE1rDVNFQQdLFFgCcw4EAgAeBUpIOxAWHCcO",
    },
    {
      key: "moderate",
      label: "Moderate",
      points: 10,
      world: "Dimension: (5, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY\nBeeper: (1, 1); 1\nBeeper: (3, 1); 1\nBeeper: (5, 1); 1",
      prompt: "Flip every corner in the row: at each of the five corners, if a beeper is present pick it up, otherwise put one down. Finish on <code>(5, 1)</code>.",
      starter: "function main(k) {\n  \n}\n",
      check: ["beepers","position"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WVwQTUk0ASBdTWBALQR1IRQhMWUQZTRECSllMTFZpUxEQFghLU00KQgcBSAZUGRIiFwleBh1FGB9IDRhLEQUGD28TVBsEAE1FFmlTERAWBEEAAEEHSxRYAnMOBAIAHgVKSDsQFkENGEsMAxMBBV8KYUFSGGYNQxpXEB4KAxEABBwAFl4mQw4SFwsYBUpaEVsYEUQQDiMJABRIBBlCWnhFTEgPAFQQXU9dBhEjCQAUSAQZQlp4GA==",
    },
    {
      key: "complex",
      label: "Complex",
      points: 15,
      world: "Dimension: (4, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY\nBeeper: (2, 1); 1\nBeeper: (4, 1); 1",
      prompt: "Walk across all four corners. At each one, paint it <code>\"Blue\"</code> if it has a beeper, and <code>\"Red\"</code> if it doesn't.",
      starter: "function main(k) {\n  \n}\n",
      check: ["colors","position"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WVwQTUk0ASBdTWBALQR1IRQhMWUQeTRECSllMTFZpUxEQFghLU00KQgcBSAZUGRIiFwleBh1FGB9IDRhLEQ0MClk1XhkPFxdEDyEfRFUUSBZ5RUFMRQFBBVRLClwVDUQNB3JfRA9IAU1DPgAAD18KYUFSRUxGTR5eRlNJBEhvQUwYbg1WWA1BWg5CTwYWQVVEEn0BABIJCxAFXxhLClwVDUQNB3JfRA9IAU1DLgkRSFQYUGtSRQlBEBYRWxgRTBoLFS8KFkMTQ0NDIAAID0pIO00=",
    },
  ],
};

export default lesson06;
