/**
 * Assignment "lesson-15" — companion to lessons/15-maps.html (Maps).
 *
 * GENERATED by tools/gen-lesson-assignments.js — edit the problem there and
 * regenerate; do not hand-edit the sealed solutions below. Each of the three
 * problems (simple / moderate / complex) stores its reference solution SEALED
 * (see tools/seal.js). The plaintext solutions live in the generator.
 */
export const lesson15 = {
  id: "lesson-15",
  lessonNum: 15,
  lessonSlug: "15-maps",
  lessonTitle: "Maps",
  title: "Assignment 15 · Maps",
  points: 30,
  problems: [
    {
      key: "simple",
      label: "Simple",
      points: 5,
      world: "Dimension: (1, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Build a <code>Map</code> from letter to a count — <code>new Map([[\"a\", 3]])</code> — and drop <code>map.get(\"a\")</code> beepers.",
      starter: "function main(k) {\n  const map = new Map([[\"a\", 3]]);\n  \n}\n",
      check: ["beepers"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WUgQPARFMQAIDEQ0WD0gERSwNFUx2LRMKQ15FX3A+Wgo6FkFOHAsSGEUKDUsRBgACSwtIF1sTURRIFnlFQQoKFg1eXQ4VUgxMEENDChBfQRFTC1pMDE8GXxEATwIQGG8GFkFVREkESG8c",
    },
    {
      key: "moderate",
      label: "Moderate",
      points: 10,
      world: "Dimension: (3, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "The map <code>new Map([[1, 2], [2, 0], [3, 3]])</code> gives a beeper count per corner number. Walk east and drop <code>counts.get(i)</code> beepers on corner <code>i</code> (1-based).",
      starter: "function main(k) {\n  const counts = new Map([[1, 2], [2, 0], [3, 3]]);\n  \n}\n",
      check: ["beepers","position"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WUgQPARFMTgwGX0RFQRBTCwQbRSlMBhkwOkNJTB8+XxFrBE0NQzhNTD5XAVYCNjxbXmYNQxVeQhZJQRYRQQVFWQ1HCksIUllRDVBIEVkdSgRTHmtMRUQNEF4ZQVoJCVlDGRENFlEWUw9BUEUHQgNfHxJcAglZSxoYCxYLBlhMQQdLFFgCcw4EAgAeBUpIOxAWQQ0aA0FEDEQRVgJCQRlLAUIVFhkZDWsNUxhrEQ==",
    },
    {
      key: "complex",
      label: "Complex",
      points: 15,
      world: "Dimension: (3, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Use a <code>Map</code> as a palette lookup: <code>new Map([[1,\"Red\"],[2,\"Green\"],[3,\"Blue\"]])</code>. The array <code>[2, 3, 1]</code> gives a palette key per corner. Walk east and paint corner <code>i</code> with <code>palette.get(keys[i])</code>.",
      starter: "function main(k) {\n  const palette = new Map([[1, \"Red\"], [2, \"Green\"], [3, \"Blue\"]]);\n  const keys = [2, 3, 1];\n  \n}\n",
      check: ["colors","position"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WUgQPARFMXQIfVERCBA1ORQ8JEkRgF0FDOilUQA1BIVRUFDwBUz5TQEVGagRUDg9QOEANOEAdEBQjQQYAQzE4TRZ8EUsCHQsfWUMYVElFQRBTPlNARVcBVgA2WnhFTEsMAREYWgRZUwxBUUVUFlZYS11SDglUEF1dVVgGWRteQQVOTwRWSmFBUkVMRk0DUFlYFW4cFw8JF0xdF10OFQYAQkoGBxlbUxheKAw8RUxfJ1YRS0EbA0wFClMNEF0EVABLDQkLA1keEUZBQ0xMRk0eXkZTSQRIb0FMGG5Q",
    },
  ],
};

export default lesson15;
