/**
 * Assignment "lesson-13" — companion to lessons/13-arrays.html (Arrays).
 *
 * GENERATED by tools/gen-lesson-assignments.js — edit the problem there and
 * regenerate; do not hand-edit the sealed solutions below. Each of the three
 * problems (simple / moderate / complex) stores its reference solution SEALED
 * (see tools/seal.js). The plaintext solutions live in the generator.
 */
export const lesson13 = {
  id: "lesson-13",
  lessonNum: 13,
  lessonSlug: "13-arrays",
  lessonTitle: "Arrays",
  title: "Assignment 13 · Arrays",
  points: 30,
  problems: [
    {
      key: "simple",
      label: "Simple",
      points: 5,
      world: "Dimension: (1, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Sum the array <code>[1, 2, 3]</code> and drop that many beepers (6 total).",
      starter: "function main(k) {\n  const nums = [1, 2, 3];\n  \n}\n",
      check: ["beepers"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WUgQPARFMQxYeQhALQXZCSUFeSUQeKwphQVIJCVlDAERdFlwNQ15rTEUCQgQRQwIdCx9ZQx0RX1BBQwYIEkVFF1gbEUBcUgtXJ0NTV19EQQUfABVMDEQQVgFQQRtFUA0QBlwLFggGWExBB0sUWAJzDgQCAB4FSkg7TQ==",
    },
    {
      key: "moderate",
      label: "Moderate",
      points: 10,
      world: "Dimension: (4, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "The array <code>[1, 3, 2, 4]</code> says how many beepers each corner needs. Walk east and drop <code>counts[i]</code> beepers on corner <code>i</code>.",
      starter: "function main(k) {\n  const counts = [1, 3, 2, 4];\n  \n}\n",
      check: ["beepers","position"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WUgQPARFMTgwGX0RFQRBTPlBARVcBVgNHQUY4VydDU1dfREEFHwAVTAxEEFYBUEEbRVANABxEXkISAx8ADwsRDBZWWEBKW0UXJ0NTERBQDl9TTQ0JEURHVgxLUUlFBg1fU1JfQw9ZAD4IMV5ER10aQkEZSxxYFzFUVUYEX1tMWmZFRA1WWA1BWgxMEUMQXkVYFV5dCQQCAhBFVhxLUFtFBwMOHEdVHkgWeUVBEW8Z",
    },
    {
      key: "complex",
      label: "Complex",
      points: 15,
      world: "Dimension: (4, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "The array <code>[\"Red\", \"Blue\", \"Red\", \"Green\"]</code> gives a colour per corner. Walk east and paint corner <code>i</code> with <code>colors[i]</code>.",
      starter: "function main(k) {\n  const colors = [\"Red\", \"Blue\", \"Red\", \"Green\"];\n  \n}\n",
      check: ["colors","position"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WUgQPARFMTgwfXkJFQRBTPkM+AAAPWhFJIx4QCQ9PUxNiUwUPX0VDKxcBSBgTNlp4RUxLDAERGFoEWVMMQVFFVBZWWEtdUgYDQQwBQh5aBEMUEQlXRQ0GXRhLGnhFTA1DGB9AVwhDByYOHgsBX15SBA0dFx92Ci4YCzxBDVNFCApFTERWDUsCHQkDXxBdXVVYBlkbRUxMVE0NHR8GDgQARARYeREQS2tQ",
    },
  ],
};

export default lesson13;
