/**
 * Assignment "lesson-17" — companion to lessons/17-recursion.html (Recursion).
 *
 * GENERATED by tools/gen-lesson-assignments.js — edit the problem there and
 * regenerate; do not hand-edit the sealed solutions below. Each of the three
 * problems (simple / moderate / complex) stores its reference solution SEALED
 * (see tools/seal.js). The plaintext solutions live in the generator.
 */
export const lesson17 = {
  id: "lesson-17",
  lessonNum: 17,
  lessonSlug: "17-recursion",
  lessonTitle: "Recursion",
  title: "Assignment 17 · Recursion",
  points: 30,
  problems: [
    {
      key: "simple",
      label: "Simple",
      points: 5,
      world: "Dimension: (6, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Write a <strong>recursive</strong> <code>walk(k)</code>: if the front is clear, move once and call <code>walk(k)</code> again. This carries Karel to the wall at <code>(6, 1)</code>.",
      starter: "function walk(k) {\n  \n}\n\nfunction main(k) {\n  \n}\n",
      check: ["position"],
      solution: "DRQcBhhEDB0RR1cNRlsOSEwebg1WWA1BWg5CSxEcX0R/Em4fAAAeTU0EVkphQVJFTEZNHl5GU0kESG9BTEVEWhddAEkZTFcnQ1NMOktrJxUQDw8RDUIYEQYAGwtERkpTSjoWQVoSCQpEDk0WfEw=",
    },
    {
      key: "moderate",
      label: "Moderate",
      points: 10,
      world: "Dimension: (1, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Write a recursive <code>putN(k, n)</code>: if <code>n</code> is 0 stop; otherwise drop one beeper and recurse with <code>n - 1</code>. Call <code>putN(k, 5)</code>.",
      starter: "function putN(k, n) {\n  \n}\n\nfunction main(k) {\n  \n}\n",
      check: ["beepers"],
      solution: "DRQcBhhEDB0RQEMVY1sOTUwLTQ0NO0tBGwNMBQ1TDQ0WUQRTFwQYEBZDTTtLQRlLHFgXMVRVRgRfW0xaZkVEXQNFJUkZSUxDQ14RAR9aJw5vawoQCk4CWAQPUggNRA1bWhkWGidTRREZESoFHR1LVFteZlA=",
    },
    {
      key: "complex",
      label: "Complex",
      points: 15,
      world: "Dimension: (5, 1)\nKarel: (1, 1); east\nBeeperBag: 0\nBeeper: (1, 1); 1\nBeeper: (2, 1); 1\nBeeper: (3, 1); 1\nBeeper: (4, 1); 1\nBeeper: (5, 1); 1",
      prompt: "Write a recursive <code>collect(k)</code>: pick up any beeper on the current corner, then — if the front is clear — move and recurse. It clears the whole corridor and stops at the wall.",
      starter: "function collect(k) {\n  \n}\n\nfunction main(k) {\n  \n}\n",
      check: ["beepers","position"],
      solution: "DRQcBhhEDB0RU1kNQRYGFUQOTQ0NO0tBGwNMBQhdU1VTEUgBFjEeABdIGEVDSFtFBwMTGlJbdARIAwATRExfJ1YRAgdSTQcDBQFeXkIoXjAJBA0XTARfERBrUkVMDQhdXF9ABAVaXmtMRUQNFV4HDRcGGAUIWgo6FkFQeRhrZgMRQxVFAg4cRQFMCh0ZWx9BVnlFQQ8KCEETUh9JGUxXJx4=",
    },
  ],
};

export default lesson17;
