/**
 * Assignment "lesson-14" — companion to lessons/14-objects.html (Objects).
 *
 * GENERATED by tools/gen-lesson-assignments.js — edit the problem there and
 * regenerate; do not hand-edit the sealed solutions below. Each of the three
 * problems (simple / moderate / complex) stores its reference solution SEALED
 * (see tools/seal.js). The plaintext solutions live in the generator.
 */
export const lesson14 = {
  id: "lesson-14",
  lessonNum: 14,
  lessonSlug: "14-objects",
  lessonTitle: "Objects",
  title: "Assignment 14 · Objects",
  points: 30,
  problems: [
    {
      key: "simple",
      label: "Simple",
      points: 5,
      world: "Dimension: (1, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "The object <code>{ beepers: 4 }</code> describes a corner. Read its <code>beepers</code> property and drop that many beepers.",
      starter: "function main(k) {\n  const corner = { beepers: 4 };\n  \n}\n",
      check: ["beepers"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WUgQPARFMTgwBX1VEQRBTHkEOAAFdE0MYW1JRTFBYeREQUA5fU00NCRFERFYMS1FJRQUNX1NSX0QPSAFLAwkAFEgEQlBBG05HBEMYH0BDFW8WABEJF0wETTsW",
    },
    {
      key: "moderate",
      label: "Moderate",
      points: 10,
      world: "Dimension: (4, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "The object <code>{ avenue: 4, street: 1 }</code> is Karel's target. Use its <code>avenue</code> property to move there, ending on <code>(4, 1)</code>.",
      starter: "function main(k) {\n  const target = { avenue: 4, street: 1 };\n  \n}\n",
      check: ["position"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WUgQPARFMWQIBVlVCQRBTHkENEwFDA1RRQUZJTF4XAVRVQlsNQkUcV29EDRBeGUFaCQlZQxoRDRZQFlMMQVBFEEwEVg4VXAQaSA0GVAsWCAZYTEEHSwlCAFRDSElvEQ==",
    },
    {
      key: "complex",
      label: "Complex",
      points: 15,
      world: "Dimension: (3, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "An array of objects describes each corner: <code>[{color:\"Red\",beepers:1}, {color:\"Blue\",beepers:2}, {color:\"Green\",beepers:0}]</code>. Walk east; at each corner paint <code>plan[i].color</code> and drop <code>plan[i].beepers</code> beepers.",
      starter: "function main(k) {\n  const plan = [\n    { color: \"Red\", beepers: 1 },\n    { color: \"Blue\", beepers: 2 },\n    { color: \"Green\", beepers: 0 },\n  ];\n  \n}\n",
      check: ["beepers","colors","position"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WUgQPARFMXQ8SXxALQXZ5RUFMRR8NFV4HDgBfTA8xFlUSGkFPFgARCRcXF1YASxxeb0wNQ1NKEFUOQRwXW0xHJkEDVElNUgcJSBMWQ0MMQR9TGE1mRUQNVkpLAh0JA19ZUxN3RARIHUdNTAcBSAZUGRJIRVwNHl87EBY8FnlFQQoKFg1eXQ4VUgxMEENDChBfQRFTFQ0NC0pBE18MFRpeTERIWBgQTWsNU0VBB0sUTB9fHyIdFwJIEVtBXFcPdho4Tw8KCEIEGFBrUkVMDQUcQxAeDUgHRQtMWEQdTREBQU5FHEECHWpZa09PFgARCRcXFlZbQEpbRQcDEwZFclMEXRYXSUVebg1WEUsIFEVERENPEUBaAENdCQQCAhBFVhxLUFtFBwMOHEdVHkgWeUVBEW8Z",
    },
  ],
};

export default lesson14;
