/**
 * Assignment "lesson-03" — companion to lessons/03-if.html (Making Decisions with if).
 *
 * GENERATED by tools/gen-lesson-assignments.js — edit the problem there and
 * regenerate; do not hand-edit the sealed solutions below. Each of the three
 * problems (simple / moderate / complex) stores its reference solution SEALED
 * (see tools/seal.js). The plaintext solutions live in the generator.
 */
export const lesson03 = {
  id: "lesson-03",
  lessonNum: 3,
  lessonSlug: "03-if",
  lessonTitle: "Making Decisions with if",
  title: "Assignment 3 · Making Decisions with if",
  points: 50,
  problems: [
    {
      key: "simple",
      label: "Simple",
      points: 5,
      world: "Dimension: (1, 1)\nKarel: (1, 1); east\nBeeperBag: 0\nBeeper: (1, 1); 1",
      prompt: "There may or may not be a beeper here. Using a single <code>if</code>, pick the beeper up <strong>only if</strong> one is present.",
      starter: "function main(k) {\n  \n}\n",
      check: ["beepers"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WWA1BWg5CTwYWQVVEEn0BABIJCxAFXxhLGnhFTA1DGB9AXwJGMQAEHAAWBV8KYUFSGGZQ",
    },
    {
      key: "moderate",
      label: "Moderate",
      points: 10,
      world: "Dimension: (3, 1)\nKarel: (1, 1); east\nBeeperBag: 0\nBeeper: (1, 1); 1\nBeeper: (3, 1); 1",
      prompt: "Some corners have a beeper, some don't. Visit all three corners in a row (no loop yet — write it out). At each corner, pick a beeper up only if one is present.",
      starter: "function main(k) {\n  \n}\n",
      check: ["beepers","position"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WWA1BWg5CTwYWQVVEEn0BABIJCxAFXxhLClwVBU4IMVRVRgRfW0xaZkVERlhcBBcXTUUWaVMRWVBBBRhLAwkAFEgEQjsTFxYJQxdbGBkWCgMDDAIHJwFIBlQZSVteZg1DGB9dWRdIW0xaZkVERBARQwpcBwlIExZDQ2YTSAAADxhNTQRWWkURGwYHbwYWQVVESQRIbxw=",
    },
    {
      key: "complex",
      label: "Complex",
      points: 15,
      world: "Dimension: (4, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY\nBeeper: (2, 1); 1\nBeeper: (4, 1); 1",
      prompt: "Walk across all four corners. Whenever the current corner has a beeper, paint it <code>\"Red\"</code>. Leave the beepers where they are.",
      starter: "function main(k) {\n  \n}\n",
      check: ["colors","position"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WWA1BWg5CTwYWQVVEEn0BABIJCxAFXxhLClwVDUQNB3JfRA9IAU1DPgAAD18KYUFSDkJADAVUGB9aJ1NFCApFTEZYUw4EAgAeXjMBVENTD1lbTEhMDkpdF1gFFTEKHkMGARkSZARJUUxaZkVERlhcBBcXTUUWaVMRWVBBBRhLAwkAFEgEQjsTFxYJQxdbGBkWCgMDBAgCESdCBF8OE1pHPkgHURgLPEENGEsMAxMBBV8KYUFSDAoNSxgfUlMEXRYXEjwXAV4TXx9JW0xMRk0DUFlYFW4cFw8JF0wPJFQPQ1teZlA=",
    },
    {
      key: "complex2",
      label: "Complex II",
      points: 20,
      world: "Dimension: (8, 8)\nKarel: (1, 1); east\nBeeperBag: INFINITY\nColor: (6, 1); Blue\nColor: (2, 2); Red\nColor: (4, 3); Red\nColor: (6, 3); Orange\nColor: (8, 4); Blue\nColor: (2, 5); Orange\nColor: (4, 5); Blue\nColor: (6, 5); Red\nColor: (2, 7); Red\nColor: (7, 7); Orange\nColor: (4, 8); Blue\nColor: (8, 8); Orange",
      prompt: "An 8&times;8 grid is dusted with coloured corners &mdash; some <code>\"Red\"</code>, some <code>\"Orange\"</code>, some <code>\"Blue\"</code>, the rest bare. Karel must sweep the whole grid and leave beepers to match the colour it is standing on: <strong>1</strong> beeper on every red corner, <strong>2</strong> on every orange corner, <strong>3</strong> on every blue corner, and nothing on a bare corner.\n<p>You don't have loops yet, so this is a job for <strong>functions</strong> plus <code>if</code>. Write a helper that checks the current corner's colour with <code>cornerColorIs</code> and drops the right number of beepers, and another helper that walks one full row of eight corners applying it; then call them to cover the grid boustrophedon-style &mdash; east along one street, up one, west along the next.</p>\n<p>Karel starts at <code>(1, 1)</code> facing east with an unlimited bag. Where Karel finishes doesn't matter &mdash; only the beepers are graded.</p>",
      starter: "function main(k) {\n  \n}\n",
      check: ["beepers"],
      solution: "DRQcBhhEDB0RREMTQyEMBgQRTEZfERBrUkUHAxcGQ156BEsHTUhXb0QNHR8fFAALIEgFBxkZDWsNUw5PGBAWQzpUDRVaTFcnHnk7VkMPTgcMDgJFCUwEWkMKW0UXJ0NTWFYWSUZdBg4eCwFfNV4HDgAsHwVBIVRUFEgEUx5rTEVEDR0fGxQGJwlIExZDGB9aJ1NFHGZFREQQEUMKXAYDXw0WQ3NZDUIBLBJERytfF18MBFBMRQ0YeREQFkFGXRUUGCcBSAZUGUlbXmYNQ1MRWxgRWAcnBAkVAV9eGFBrUkURJ0NTWFYWSUZdBg4eCwFfNV4HDgAsHwVBMV1FU0MEWkUaZkVEDVZaRREHES5IBgNUQh5IFnlFQUxFDwMGRB8jFwAcSBFbGAs8QQ1TRQpCFRFZNFQOERcXRARYeREQS2tQeW8HGQsHWR9eBUERFwNeECFeRx4KBFMea0xFCUwEWkMKW15mDUMYH11ZF0hbTFpmRURAF0MASRlMVydDU1oeWw5bFk1IV29EDRtQGQpaDkUWaVMRWxgMQgUASUVebg1WXAoTGU0HBFh5ERBdT0AcEwRETF8nVhEGAAAOREZKSDsQFgoDHgoXCU1NFnwRSwwTFwcFCFoKOhZBRl0IDhoATARNO0tBHwQeRksYGAs8QQ0YSwwDEwEFXwphQVIIDV8IW1oZDWtQeW8HGQsHWR9eBUEaChxrERxcdVcSWVsOSEwebg1WWkUVBxcCYQYVRRgfWidTRQpCCAtbExlCWnhFTEZNB0RCWC1IFRFJRV5uUHw7DRQcBhhEDB0RWFkRawEKDDsAF1leWkJBCW9MDRcGQ15kCEobEUkHTF8nVhEATx8KGkhLWgo6FkFZBhcPPgwDRQIZAEhJbxEnaRVEXlUVRBwLQQEEDUNeWkJBCW9MDQABXkNFM0IETQpFXm4NVlkEETQXA0AmEkJEHgoESG9BTAYWQgVCOQ4FTQcEWHkREF4OXTUXDgEyAV4CGQBISW9MDQABXkNFM0IETQpFXm4NVlkEETQXA0AmEkJEHgoESG9BTAYWQgVCOQ4FTQcEWHkREF4OXTUXDgEyAV4CGQBISW9MDQABXkNFM0IETQpFXm4NVlkEETQXA0AmEkJEHgoESG9BTAYWQgVCOQ4FTQcEWHkREF4OXTUXDgEyAV4CGQBISW9MDQABXkNFM0IETQpFXm4NVlkEETQXA0AmEkJEHgoESG9BTAYWQgVCOQ4FTQcEWHlM",
    },
  ],
};

export default lesson03;
