/**
 * Assignment "lesson-06" — companion to lessons/06-if-else.html (if / else).
 *
 * GENERATED by tools/gen-lesson-assignments.js — edit the problem there and
 * regenerate; do not hand-edit the sealed solutions below. Each of the three
 * problems (simple / moderate / complex) stores its reference solution SEALED
 * (see tools/seal.js). The plaintext solutions live in the generator.
 */
export const lesson06 = {
  id: "lesson-06",
  lessonNum: 6,
  lessonSlug: "06-if-else",
  lessonTitle: "if / else",
  title: "Assignment 6 · if / else",
  points: 50,
  problems: [
    {
      key: "simple",
      label: "Simple",
      points: 5,
      world: "Dimension: (3, 3)\nKarel: (1, 1); north\nBeeperBag: INFINITY\nBeeper: (1, 3); 1",
      prompt: "Karel starts at <code>(1, 1)</code> facing north in a 3&times;3 room. Walk north to the wall, then turn right and walk east to the far wall. At <strong>each of the two corners where a wall stops you</strong> &mdash; <code>(1, 3)</code> and <code>(3, 3)</code> &mdash; make the same decision with one <code>if</code> / <code>else</code>: if a beeper is present, pick it up; otherwise, put one down. (One of those corners has a beeper and the other doesn't, so both branches get used.) Finish on <code>(3, 3)</code>.",
      starter: "function main(k) {\n  \n}\n",
      check: ["beepers","position"],
      solution: "DRQcBhhEDB0RRFkGSh8ASQdMRFZ8EUsIFEVERk0RVFVGBF8ANRMJFgFDAhlCSFIeZg1DUxFbGBFEEA4jCQAUSAQZQlp4RUxQQxZdQ1NBVnlFQUxFDwMGRB8jFwAcSBFbGAs8QQ0ObxxmbwJYGFIfCB0LTEACGl8YXUgNCG9BTA5KQBlHDklbXmYNQxgfXVkXSFtMWmZFRFkZVgwNF00HBFh5ERBdT1kGFw8gAAJZXhhQa1JFBwMXBkNeegRLB01IV29EDR0fHxQACyBIBQcZGQ1rDVMOTwEKEkheGFBrUkUHAw4cR1UeSBZ5RUEYCgNKGlRDClteZlA=",
    },
    {
      key: "moderate",
      label: "Moderate",
      points: 10,
      world: "Dimension: (5, 4)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Karel starts at <code>(1, 1)</code> facing east in a 5&times;4 room. Walk along <strong>three</strong> walls &mdash; east along the south wall, north up the east wall, then west along the north wall &mdash; dropping a beeper on every corner Karel steps <em>onto</em> (the starting corner stays empty). Stop when Karel reaches <code>(1, 4)</code>.\n<p>Don't count the moves per side. Use one decision inside a loop, exactly as in the lesson: <code>if (k.frontIsClear())</code> move and put a beeper, <code>else</code> turn left &mdash; the walls tell Karel when to turn. The trip is 11 moves plus 2 turns, so the loop runs <strong>13</strong> times.</p>",
      starter: "function main(k) {\n  \n}\n",
      check: ["beepers","position"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WVwQTUk0ASBdTWBALQR1IRQhMWUQcRQpLCFlORQ0YeREQFkFEFUVJB0sCXxlfHygBJgBIAgEZGR9BVnlFQUxFRA0dHwYOBABEBFh5ERAWQQ1TDk8cEBBvE1QbBABNRRZpUxEQFhwNFgkSCUUfJ1YRS0FSRQcDFwZDXnoESwdNSFdvRA1WERZrUkURJx4=",
    },
    {
      key: "complex",
      label: "Complex",
      points: 15,
      world: "Dimension: (5, 4)\nKarel: (1, 1); east\nBeeperBag: INFINITY\nBeeper: (2, 1); 1\nBeeper: (4, 1); 1\nBeeper: (5, 1); 1\nBeeper: (1, 2); 1\nBeeper: (3, 2); 1\nBeeper: (2, 3); 1\nBeeper: (5, 3); 1\nBeeper: (3, 4); 1\nBeeper: (4, 4); 1",
      prompt: "Beepers are scattered across a 5&times;4 room. Visit <strong>every</strong> corner and paint each one <code>\"Blue\"</code> if it has a beeper and <code>\"Red\"</code> if it doesn't. Leave the beepers where they are.\n<p>Sweep the room like a lawnmower: east along the first street, up one, west along the next, up one, and so on &mdash; the snake from the lesson. That needs <em>two</em> <code>if</code> / <code>else</code> decisions: one at every corner (beeper or not?), and one at the end of each row, where which way Karel U-turns depends on <code>facingEast()</code>. Write them as helper functions, then let <code>main</code> alternate \"sweep a row\" and \"climb to the next row\" until all four rows are painted.</p>\n<p>Karel starts at <code>(1, 1)</code> facing east. Only the paint is graded &mdash; where Karel finishes doesn't matter.</p>",
      starter: "function main(k) {\n  \n}\n",
      check: ["colors"],
      solution: "DRQcBhhEDB0RREMTQyEMBgQRTEZfERBrUkUHAxcGQ156BEsHTUhXb0QNHR8fFAALIEgFBxkZDWsNUw5PGBAWQzpUDRVaTFcnHnk7VkMPTgcMDgJFFEwfXx8iHRcCSBFbWhkWGidTRQgKRUxGWFMOBAIAHl4zAVRDUw9ZW0xITB5uDVYRSwpcFQ1EDQdyX0QPSAFNQy4JEUhUGFBrUkURDQYfQlUWGidTRUFMDkpdF1gFFTEKHkMGARkSZARJUUxaZkVEUHxMYWsUEAJOFxpeXhYRTBoLFT4KEwUdGEsaeEVMXQIaX0R1Dl8dABNEDk0WfBFLFhoMAEhDW1oeUBNCHREoHyYISBdDQ0hbRRcnQ1MREF1PQBwTBERMXydWEUtBAgQFQxcwXkJYBF9bDkhXb0QNCzsWa3gDGUMAB1hfWEFOHwwMDjELYxNJHzMdEkRGSlNKOhZBRBVFSQdLAkwVWAUGNwQfWUtaGBBNaw1TRUEHSxBYBF8nBBQRRARYeREQFkFGXQgOGgBMBE07S0FSRQcDFwZDXnoESwdNSFdvRA0LEQ4NAQBMVmlTERAWFVgBCzMFAgxZXlpCWnhFTA1DGB9dWRdIW0xaZkVEDVZFHhMcNwVKCwcZWx9aJ1NFHGYYbicQRAUCBgwDQ0MeUFlYSUZaRRpmRURLGUNLSR4AGA0RHEYQC0EdSEUTAxJEEVYCUEEAChsGSFoRSzxBDVNFEQ0MClkkXhxJGUxXJ0NTERBVDUQeBzUDKwFVAmMEFloORRZpUxFNPEENAwQIAhE2QgEZAEhJbxE=",
    },
    {
      key: "advanced",
      label: "Advanced",
      points: 20,
      world: "Dimension: (6, 4)\nKarel: (1, 1); east\nBeeperBag: INFINITY\nColor: (2, 1); Red\nColor: (4, 1); Blue\nColor: (6, 1); Green\nColor: (1, 2); Green\nColor: (3, 2); Red\nColor: (5, 2); Blue\nColor: (2, 3); Blue\nColor: (4, 3); Green\nColor: (6, 3); Red\nColor: (1, 4); Red\nColor: (3, 4); Green\nColor: (5, 4); Blue\nBeeper: (6, 1); 1\nBeeper: (3, 2); 1\nBeeper: (4, 3); 1\nBeeper: (2, 4); 1",
      prompt: "Karel manages a 6&times;4 stock room whose corners are painted <code>\"Red\"</code>, <code>\"Green\"</code> or <code>\"Blue\"</code> (the rest are bare). Sweep every corner and stock it by colour: <strong>4</strong> beepers on a red corner, <strong>2</strong> on a green one, <strong>1</strong> on a blue one, nothing on a bare corner.\n<p>There's one more rule, and it <em>overrides</em> the colours: <strong>a corner that already holds a beeper has been stocked &mdash; leave it exactly as it is, whatever its colour.</strong> Four corners start with a single beeper; when you're done each of them must still have exactly one.</p>\n<p>Write the decision as a single <code>if</code> / <code>else if</code> chain in a helper. Think about the <strong>order</strong> of the branches: a red corner that already has a beeper makes two of your conditions true at once, and the chain runs only the first one that matches &mdash; so the branch that must win has to come first. Reuse the lesson's snake to visit every corner (a row-sweeping helper plus a <code>facingEast()</code>-aware climb).</p>\n<p>Karel starts at <code>(1, 1)</code> facing east with an unlimited bag. Only the beepers are graded &mdash; where Karel finishes doesn't matter.</p>",
      starter: "function main(k) {\n  \n}\n",
      check: ["beepers"],
      solution: "DRQcBhhEDB0RREMTQyEMBgQRTEZfERBrUkUHAxcGQ156BEsHTUhXb0QNHR8fFAALIEgFBxkZDWsNUw5PGBAWQzpUDRVaTFcnHnk7VkMPTgcMDgJFF1kZUgAiHRcCSBFbWhkWGidTRQgKRUxGWFMOBAIAHl4zAVRDUw9ZW0xITB5uDVYRS05dRQ1BERZQVE9BXgcKAgcAAA1bEQcEExMJDQoHEVFaDkMWSUEbDQVZE0cOE1IRBEhDEF5cWRRfeUVBEUUBQQVUSwgURURGTRBeQlgEXzAKDQMXLV5eEzkEFkdFBEMIOxAWQQ0VChNMTQhIAhECQU9FXBZDGhEMFlUWUwxKR0xEVnwRS0FSRUxGTQNERHQESAMAE0RMXydWEUtBD29MDR5TVFxFBA0aA0FEDkpOGUMFBAAmA0EMAXhDHkNqAQAEAkdNBFZKYUFSRUxLDAERGFoEWVMMQVFFVBZWWEtdUldXDQpYGhkWGidTRUFMRURGWEEeFTAACV0GARkZDWsNU0VBEW9EDQsRDg0BAExEBVMZWxgCQgELBB4mC0EZQyISWkcuQRYWExkfQVZ5RUFMRQ8DBkQfIxcAHEgRWxgLPEENDm8cZm8CWBhSHwgdC0xeFxxSW2QOWlsOSEwebg1WQh8OEQ4vQhEdVEIeCgRIb0FMEgxEGlRLSRlLCl8MHUV5RSJBFgQTRExNDQ07S0FSRQcDDhxHVR5IFnlFQUxFF1kZUgAiHRcCSBFbWhkNaw1TGGsRb25LA18IFRsKAg0AH1hdVDVCPQAZGDcLWl5aQkEJb0wNChURGF1PSxIGCAICIUwFRUNIW0UXJ0NTERBdT1kGFw8gAAJZXhhQa1JFTA0IXVxfQAQFWl5rTEVEDR0fHxQACyBIBQcZGQ1rDVMYQQkJF0hWSmFBUkVMWRYBX2JfBkUHTQpFXm4NVhFLClwIA1sGWxgLPEENU0UVGRcKfx9WAxVaDkUWaVMRTTwcJ3kDFAIGEEQZX0sMEwwCBQhaEUs8QQ0VChNMTQhIAhEZDgVFUQ1TSBFCWRYNT0VSV0UWQgEaQEhSHmYNQ1MRQ0IOThg3DhtNDwRNO0tBUkUPQQoeU2RZL0gLETMDEkxGXwphQVIYZg1DAEVfVQp/HBJJB0xfJws=",
    },
  ],
};

export default lesson06;
