/**
 * Assignment "lesson-02" — companion to lessons/02-functions.html (Functions).
 *
 * GENERATED by tools/gen-lesson-assignments.js — edit the problem there and
 * regenerate; do not hand-edit the sealed solutions below. Each of the three
 * problems (simple / moderate / complex) stores its reference solution SEALED
 * (see tools/seal.js). The plaintext solutions live in the generator.
 */
export const lesson02 = {
  id: "lesson-02",
  lessonNum: 2,
  lessonSlug: "02-functions",
  lessonTitle: "Functions",
  title: "Assignment 2 · Functions",
  points: 30,
  problems: [
    {
      key: "simple",
      label: "Simple",
      points: 5,
      world: "Dimension: (3, 3)\nKarel: (2, 2); north\nBeeperBag: INFINITY",
      prompt: "Karel has no built-in \"turn right\". Write a helper <code>turnRight(k)</code> (three left turns), use it to face east, then move one square to <code>(3, 2)</code>.",
      starter: "function turnRight(k) {\n  \n}\n\nfunction main(k) {\n  \n}\n",
      check: ["position","direction"],
      solution: "DRQcBhhEDB0RREMTQyEMBgQRTEZfERBrUkUHAxcGQ156BEsHTUhXb0QNHR8fFAALIEgFBxkZDWsNUw5PGBAWQzpUDRVaTFcnHnk7VkMPTgcMDgJFCUwfX0MKW0UXJ0NTRUVED38aAgkYTQ8ETTtLQRlLAUIVFhkZDWtQ",
    },
    {
      key: "moderate",
      label: "Moderate",
      points: 10,
      world: "Dimension: (5, 1)\nKarel: (3, 1); east\nBeeperBag: INFINITY",
      prompt: "Write a helper <code>turnAround(k)</code> (two left turns). Move east to the wall, turn around, and walk all the way back to <code>(1, 1)</code> facing west.",
      starter: "function turnAround(k) {\n  \n}\n\nfunction main(k) {\n  \n}\n",
      check: ["position","direction"],
      solution: "DRQcBhhEDB0RREMTQzIXDhkLAAUdGEsaeEVMRk0HREJYLUgVEUlFXm4NVlpFFQcXAmEGFUUYH1onDm9rChAKTgJYBA9SCA1EDVtaGRYaJ1NFCkIIC1sTGUJaeEVMRk0eXkZTSQRIb0FMERFfGHAZDgcLCAUIWgo6FkFGXQgOGgBMBE07S0EZSwFCFRYZGQ1rDVMOTwEKEkheGFBrUkUHAw4cR1UeSBZ5GA==",
    },
    {
      key: "complex",
      label: "Complex",
      points: 15,
      world: "Dimension: (4, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Write a helper <code>dropAndMove(k)</code> that drops a beeper and then moves one square east. Call it three times to leave beepers on corners 1, 2, and 3, finishing on <code>(4, 1)</code>.",
      starter: "function dropAndMove(k) {\n  \n}\n\nfunction main(k) {\n  \n}\n",
      check: ["beepers","position"],
      solution: "DRQcBhhEDB0RVEQOXTILBSEKEkheWkJBCW9MDQhdQUVCI0gWFQQeTU0WfBFLClwIA1sGWxgLPBwneQMUAgYQRBlfSwwTDAIFCFoRSzxBDRcXDhwkCkk7Xh0EWg5FFmlTEVREDl0yCwUhChJIXlpCWnhFTEkRHEFxWAVgHBMERA5NFnxM",
    },
  ],
};

export default lesson02;
