/**
 * Assignment "lesson-05" — companion to lessons/05-while-loops.html (The while Loop).
 *
 * GENERATED by tools/gen-lesson-assignments.js — edit the problem there and
 * regenerate; do not hand-edit the sealed solutions below. Each of the three
 * problems (simple / moderate / complex) stores its reference solution SEALED
 * (see tools/seal.js). The plaintext solutions live in the generator.
 */
export const lesson05 = {
  id: "lesson-05",
  lessonNum: 5,
  lessonSlug: "05-while-loops",
  lessonTitle: "The while Loop",
  title: "Assignment 5 · The while Loop",
  points: 30,
  problems: [
    {
      key: "simple",
      label: "Simple",
      points: 5,
      world: "Dimension: (7, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Karel doesn't know how long the corridor is. Use a <code>while</code> loop to move east until the front is blocked, stopping at the far wall.",
      starter: "function main(k) {\n  \n}\n",
      check: ["position"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WRgMIHgBMBQhdV0JZD1k6FiIAAAVfXhhCQQlvTA1DU1oeWw5bFk1IV29EDQs7Fg==",
    },
    {
      key: "moderate",
      label: "Moderate",
      points: 10,
      world: "Dimension: (1, 1)\nKarel: (1, 1); east\nBeeperBag: 0\nBeeper: (1, 1); 5",
      prompt: "There is a pile of beepers on Karel's corner. Use a <code>while</code> loop to pick them <strong>all</strong> up.",
      starter: "function main(k) {\n  \n}\n",
      check: ["beepers"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WRgMIHgBMBQhdU1VTEUgBFjEeABdIGEVDSFtFFydDUxEQXU9dGgYKLgABXRNDQ0hJb0wNHnlM",
    },
    {
      key: "complex",
      label: "Complex",
      points: 15,
      world: "Dimension: (6, 1)\nKarel: (1, 1); east\nBeeperBag: 0\nBeeper: (1, 1); 1\nBeeper: (2, 1); 1\nBeeper: (3, 1); 1\nBeeper: (4, 1); 1\nBeeper: (5, 1); 1\nBeeper: (6, 1); 1",
      prompt: "Every corner holds a beeper. Walk east to the wall, collecting <strong>every</strong> beeper along the way, and stop on the last corner.",
      starter: "function main(k) {\n  \n}\n",
      check: ["beepers","position"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WRgMIHgBMBRcBRFUfQVZ5RUFMRRNFH10OQVoOQk8GFkFVRBJ9AQASCQsQBV8YSwpcFQVOCDFUVUYEX1tMWmZFRA1WWA1BWkQHAwUBXl5CKF4wCQQNF0wEXxEJExcEBxZpUxEQFgoDHgoXCU1NFnwRSxx4GA==",
    },
  ],
};

export default lesson05;
