/**
 * Assignment "lesson-12" — companion to lessons/12-strings.html (Strings).
 *
 * GENERATED by tools/gen-lesson-assignments.js — edit the problem there and
 * regenerate; do not hand-edit the sealed solutions below. Each of the three
 * problems (simple / moderate / complex) stores its reference solution SEALED
 * (see tools/seal.js). The plaintext solutions live in the generator.
 */
export const lesson12 = {
  id: "lesson-12",
  lessonNum: 12,
  lessonSlug: "12-strings",
  lessonTitle: "Strings",
  title: "Assignment 12 · Strings",
  points: 30,
  problems: [
    {
      key: "simple",
      label: "Simple",
      points: 5,
      world: "Dimension: (1, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Use a string's <code>.length</code>: for the word <code>\"Karel\"</code>, drop one beeper per letter (5 in total).",
      starter: "function main(k) {\n  const word = \"Karel\";\n  \n}\n",
      check: ["beepers"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WUgQPARFMWgwBVRALQQ84BBMJCUYWfBFLBx0XTAUPFkUQX0EQU1VaTAxEEVZGBBMWSwBIDRRFWA1BRFhOSEwOSl0DRSkEFxUJX0taCjpL",
    },
    {
      key: "moderate",
      label: "Moderate",
      points: 10,
      world: "Dimension: (1, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Loop over the characters of <code>\"beeper\"</code> and count how many are the letter <code>\"e\"</code>. Drop that many beepers (there are 3).",
      starter: "function main(k) {\n  const word = \"beeper\";\n  \n}\n",
      check: ["beepers"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WUgQPARFMWgwBVRALQQ8RAAQcABYPTTtLQR4AGA0AHEReQkEQU1VaZkVESxlDS0kRCgJeF1NSEFkHDQQKEwhMRFZ8EUtBUgwKDUsQEQ0LXA1RAENFRQdCA18fSlleZg1DDjsQFgdCAUVJAAAQDR8RVkFCXkxEQ08RU1kUQwdeQQVOTwRWWkURBxEuSAYDVEIeSBZ5GA==",
    },
    {
      key: "complex",
      label: "Complex",
      points: 15,
      world: "Dimension: (5, 5)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Treat the string <code>\"MMLM\"</code> as instructions: <code>\"M\"</code> means move, <code>\"L\"</code> means turn left. Run each character in order. Karel should finish at <code>(3, 2)</code> facing north.",
      starter: "function main(k) {\n  const cmds = \"MMLM\";\n  \n}\n",
      check: ["position","direction"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WUgQPARFMTg4XQhALQQ8+KC0hR18nVhENDgBFRE4MHUJEFgINHANBDwgAXl8REGtSRUwNChURGFVBEE5YQU4oRgRWWkUMHRMJBUpIOxAWQQ0WCRIJRQ1LVhkIQU9YUQ1BPxMZFgoDBxATAikBSwIZQlp4RUxQaQ4=",
    },
  ],
};

export default lesson12;
