/**
 * Assignment "lesson-18" — companion to lessons/18-error-handling.html (Error Handling).
 *
 * GENERATED by tools/gen-lesson-assignments.js — edit the problem there and
 * regenerate; do not hand-edit the sealed solutions below. Each of the three
 * problems (simple / moderate / complex) stores its reference solution SEALED
 * (see tools/seal.js). The plaintext solutions live in the generator.
 */
export const lesson18 = {
  id: "lesson-18",
  lessonNum: 18,
  lessonSlug: "18-error-handling",
  lessonTitle: "Error Handling",
  title: "Assignment 18 · Error Handling",
  points: 30,
  problems: [
    {
      key: "simple",
      label: "Simple",
      points: 5,
      world: "Dimension: (2, 1)\nKarel: (2, 1); east\nBeeperBag: INFINITY",
      prompt: "Karel faces a wall, so <code>move()</code> will throw. Wrap it in <code>try</code> / <code>catch</code>: try to move, and if it fails, turn left instead. Karel should end at <code>(2, 1)</code> facing north.",
      starter: "function main(k) {\n  \n}\n",
      check: ["position","direction"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WRRkYUh5mDUNTEVsYDEIFAElFXm4NVkxLAhMRD0VDW1QZFhonU0VBTA5KWQNDBS0XAxgFSkg7EBYcJw4=",
    },
    {
      key: "moderate",
      label: "Moderate",
      points: 10,
      world: "Dimension: (6, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Instead of checking <code>frontIsClear()</code>, keep moving forever inside a <code>try</code> and let the wall collision's error stop you. Catch it so the program ends cleanly on <code>(6, 1)</code>.",
      starter: "function main(k) {\n  \n}\n",
      check: ["position"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WRRkYUh5mDUNTEUdeCEEWRUkYFxFIXxEATx8KGkhLWgo6FkFQUwYAGAYMDV5UQkEJb0wNQ1MeHxYTSBIGCQkBRFkeVEsWEwkAJ0NTTDpL",
    },
    {
      key: "complex",
      label: "Complex",
      points: 15,
      world: "Dimension: (5, 1)\nKarel: (1, 1); east\nBeeperBag: 0\nBeeper: (1, 1); 1\nBeeper: (3, 1); 1\nBeeper: (5, 1); 1",
      prompt: "Some corners are empty, so <code>pickBeeper()</code> sometimes throws. Walk all five corners and, at each, <code>try</code> to pick a beeper and <code>catch</code> the failure when there isn't one. End on <code>(5, 1)</code> with every beeper collected.",
      starter: "function main(k) {\n  \n}\n",
      check: ["beepers","position"],
      solution: "DRQcBhhEDB0RXVcIQ1sOSEwebg1WVwQTUk0ASBdTWBALQR1IRQhMWUQYTRECSllMTFZpUxEQFhVfCkUaZkVEDVYRSwpcFQVOCDFUVUYEX1tMWmZFRA1WTEsCExEPRUNbVBkWGidTRUFMRUQCWREFDlIHCUgTFkMQXgRfFm9BTEVEUHwRS0FSDAoNSxoRDBZVBFMOTwEKEkheGFBrUkURJx4=",
    },
  ],
};

export default lesson18;
