/**
 * Assignment "lesson-07" — companion to lessons/07-parameters.html (Parameters).
 *
 * GENERATED by tools/gen-lesson-assignments.js — edit the problem there and
 * regenerate; do not hand-edit the sealed solutions below. Each of the three
 * problems (simple / moderate / complex) stores its reference solution SEALED
 * (see tools/seal.js). The plaintext solutions live in the generator.
 */
export const lesson07 = {
  id: "lesson-07",
  lessonNum: 7,
  lessonSlug: "07-parameters",
  lessonTitle: "Parameters",
  title: "Assignment 7 · Parameters",
  points: 30,
  problems: [
    {
      key: "simple",
      label: "Simple",
      points: 5,
      world: "Dimension: (5, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Write <code>moveN(k, n)</code> that moves Karel <code>n</code> squares. Call <code>moveN(k, 4)</code> to reach <code>(5, 1)</code>.",
      starter: "function moveN(k, n) {\n  \n}\n\nfunction main(k) {\n  \n}\n",
      check: ["position"],
      solution: "DRQcBhhEDB0RXVkXSD1NCkBFCgRWSmFBUgMDX0NbXVVCQURTWEFcXkREVg1LD0lFBQZIWhFbGAxCBQBJRV5uUHw7DRQcBhhEDB0RXVcIQ1sOSEwebg1WXAQXFytERk9TBRkNa1A=",
    },
    {
      key: "moderate",
      label: "Moderate",
      points: 10,
      world: "Dimension: (1, 1)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Write <code>putN(k, n)</code> that drops <code>n</code> beepers on the current corner. Call <code>putN(k, 5)</code>.",
      starter: "function putN(k, n) {\n  \n}\n\nfunction main(k) {\n  \n}\n",
      check: ["beepers"],
      solution: "DRQcBhhEDB0RQEMVY1sOTUwLTQ0NO0tBFAoeDUsfVEQWCA1ORVFXRQ0NShEFWlIMRwZKU1oeRhRZMQAEHAAWBV8KYRx4bwpYDRBFWVkPDR4ECAJNDwRWSmFBUhUZWS1bWhwWVARIbxw=",
    },
    {
      key: "complex",
      label: "Complex",
      points: 15,
      world: "Dimension: (4, 4)\nKarel: (1, 1); east\nBeeperBag: INFINITY",
      prompt: "Reuse <code>moveN(k, n)</code> to draw an L: move 3 east to <code>(4, 1)</code>, turn to face north, move 3 up to <code>(4, 4)</code>, and drop a beeper. Finish facing north.",
      starter: "function moveN(k, n) {\n  \n}\n\nfunction main(k) {\n  \n}\n",
      check: ["beepers","position","direction"],
      solution: "DRQcBhhEDB0RXVkXSD1NCkBFCgRWSmFBUgMDX0NbXVVCQURTWEFcXkREVg1LD0lFBQZIWhFbGAxCBQBJRV5uUHw7DRQcBhhEDB0RXVcIQ1sOSEwebg1WXAQXFytERk9TAhkNaw1TDk8YEBZDOlQNFVpMVydDU1xfQARjWw5NTFZNFnwRSwpcFRlZIRZUQFMTBVpeaxE=",
    },
  ],
};

export default lesson07;
